const categoriesData = [
    { checkboxId: 'safe', layerName: 'Safe' },
    { checkboxId: 'computer', layerName: 'Computer' },
    { checkboxId: 'boss', layerName: 'Boss' },
    { checkboxId: 'paidExtract', layerName: 'Paid Extract' },
    { checkboxId: 'industrialElevator', layerName: 'Industrial Elevator' },
    { checkboxId: 'randomExtract', layerName: 'Random Extract' },
    { checkboxId: 'conditionalExtract', layerName: 'Conditional Extract' },
    { checkboxId: 'normalExtract', layerName: 'Normal Extract' },
    { checkboxId: 'travelBag', layerName: 'Travel Bag' },
    { checkboxId: 'smallSafebox', layerName: 'Small Safebox' },
    { checkboxId: 'computerCase', layerName: 'Computer Case' },
    { checkboxId: 'lgWeaponCrate', layerName: 'LG Weapon Crate' },
    { checkboxId: 'ammoCrate', layerName: 'Ammo Crate' },
    { checkboxId: 'toolCabinet', layerName: 'Tool Cabinet' },
    { checkboxId: 'lgToolBox', layerName: 'LG Tool Box' },
    { checkboxId: 'labCoat', layerName: 'Lab Coat' },
    { checkboxId: 'clothing', layerName: 'Clothing' },
    { checkboxId: 'militaryMedkit', layerName: 'Military Medkit' },
    { checkboxId: 'medicalPile', layerName: 'Medical Pile' },
    { checkboxId: 'briefcase', layerName: 'Briefcase' },
    { checkboxId: 'premiumStorage', layerName: 'Premium Storage' },
    { checkboxId: 'drawers', layerName: 'Drawers' },
    { checkboxId: 'courierCarton', layerName: 'Courier Carton' },
    { checkboxId: 'flightCase', layerName: 'Flight Case' },
    { checkboxId: 'dumpster', layerName: 'Dumpster' },
    { checkboxId: 'fieldSupply', layerName: 'Field Supply' },
    { checkboxId: 'birdNest', layerName: 'Bird Nest' },
    { checkboxId: 'stash', layerName: 'Stash' },
    { checkboxId: 'suitcase', layerName: 'Suitcase' },
    { checkboxId: 'spawn', layerName: 'Spawn' },
    { checkboxId: 'server', layerName: 'Server' },
    { checkboxId: 'weaponCrate', layerName: 'Weapon Crate' },
    { checkboxId: 'cementTruck', layerName: 'Cement Truck' },
    { checkboxId: 'keycardDoor', layerName: 'Keycard Door' },
    // Add more categories here
];