const markersData = [
    {//Computer
        category: 'Computer', // For marker toggle functionality. Should be a category in categoriesData.js
        coordinates: [1715, 1679], // Raw pixel coordinates found by hovering over map image in programs like Gimp or Photoshop
        iconUrl: '../images/icons/containers/computer-icon.webp', // Path to the desired marker icon
        tooltipText: 'COMPUTER', // The text that will appear next to the mouse when hovering over the icon
        popupText: 'Possible computer spawn', // Text in popup. WIP
        height: 'up', // 'up' adds an upwards chevron icon to the tooltip indicating the marker location is above ground level. 'down' is below ground level.
        locked: false, // 'true' adds a locked door icon to the tooltip, indicating the marker is found behind a keycard door
    },
    {//Computer
        category: 'Computer',
        coordinates: [2517, 1250],
        iconUrl: '../images/icons/containers/computer-icon.webp',
        tooltipText: 'COMPUTER',
        popupText: 'Possible computer spawn',
        height: 'up',
        locked: false,
    },
    {//Computer
        category: 'Computer',
        coordinates: [1753, 1054],
        iconUrl: '../images/icons/containers/computer-icon.webp',
        tooltipText: 'COMPUTER',
        popupText: 'Computer always spawns?',
        height: 'up',
        locked: false,
    },
    {//Computer
        category: 'Computer',
        coordinates: [1769, 1066],
        iconUrl: '../images/icons/containers/computer-icon.webp',
        tooltipText: 'COMPUTER',
        popupText: 'Possible computer spawn',
        height: '',
        locked: false,
    },
    {//Computer
        category: 'Computer',
        coordinates: [1755, 1187],
        iconUrl: '../images/icons/containers/computer-icon.webp',
        tooltipText: 'COMPUTER',
        popupText: 'Possible computer spawn',
        height: '',
        locked: false,
    },
    {//Computer
        category: 'Computer',
        coordinates: [1900, 1492],
        iconUrl: '../images/icons/containers/computer-icon.webp',
        tooltipText: 'COMPUTER',
        popupText: 'Possible computer spawn',
        height: '',
        locked: false,
    },
    {//Computer
        category: 'Computer',
        coordinates: [1850, 1765],
        iconUrl: '../images/icons/containers/computer-icon.webp',
        tooltipText: 'COMPUTER',
        popupText: 'Possible computer spawn',
        height: 'up',
        locked: false,
    },
    {//Computer
        category: 'Computer',
        coordinates: [2576, 1175],
        iconUrl: '../images/icons/containers/computer-icon.webp',
        tooltipText: 'COMPUTER',
        popupText: 'Event loot',
        height: '',
        locked: false,
    },
    {//Computer
        category: 'Computer',
        coordinates: [2626, 1196],
        iconUrl: '../images/icons/containers/computer-icon.webp',
        tooltipText: 'COMPUTER',
        popupText: 'Possible computer spawn',
        height: '',
        locked: false,
    },
    {//Computer
        category: 'Computer',
        coordinates: [2516, 1203],
        iconUrl: '../images/icons/containers/computer-icon.webp',
        tooltipText: 'COMPUTER',
        popupText: 'Computer behind keycard door',
        height: 'up',
        locked: true,
    },
    {//Computer
        category: 'Computer',
        coordinates: [2724, 1244],
        iconUrl: '../images/icons/containers/computer-icon.webp',
        tooltipText: 'COMPUTER',
        popupText: 'Possible computer spawn',
        height: '',
        locked: false,
    },
    {//Computer
        category: 'Computer',
        coordinates: [2689, 1316],
        iconUrl: '../images/icons/containers/computer-icon.webp',
        tooltipText: 'COMPUTER',
        popupText: 'Possible computer spawn',
        height: '',
        locked: false,
    },
    {//Computer
        category: 'Computer',
        coordinates: [2698, 1358],
        iconUrl: '../images/icons/containers/computer-icon.webp',
        tooltipText: 'COMPUTER',
        popupText: 'Computer behind keycard door',
        height: '',
        locked: true,
    },
    {//Computer
        category: 'Computer',
        coordinates: [2709, 2012],
        iconUrl: '../images/icons/containers/computer-icon.webp',
        tooltipText: 'COMPUTER',
        popupText: 'Possible computer spawn',
        height: '',
        locked: false,
    },
    {//Computer
        category: 'Computer',
        coordinates: [2720, 1997],
        iconUrl: '../images/icons/containers/computer-icon.webp',
        tooltipText: 'COMPUTER',
        popupText: 'Possible computer spawn',
        height: '',
        locked: false,
    },
    {//Computer
        category: 'Computer',
        coordinates: [3406, 2552],
        iconUrl: '../images/icons/containers/computer-icon.webp',
        tooltipText: 'COMPUTER',
        popupText: 'Possible computer spawn',
        height: '',
        locked: false,
    },
    {//Computer
        category: 'Computer',
        coordinates: [3527, 2349],
        iconUrl: '../images/icons/containers/computer-icon.webp',
        tooltipText: 'COMPUTER',
        popupText: 'Possible computer spawn',
        height: 'up',
        locked: false,
    },
    {//Computer
        category: 'Computer',
        coordinates: [2770, 1252],
        iconUrl: '../images/icons/containers/computer-icon.webp',
        tooltipText: 'COMPUTER',
        popupText: 'Computer always spawns. Opens door to its right.',
        height: 'up',
        locked: false,
    },



    {//Safe
        category: 'Safe',
        coordinates: [1715, 1087],
        iconUrl: '../images/icons/containers/safe-icon.webp',
        tooltipText: 'SAFE',
        popupText: 'Possible safe spawn',
        height: 'up',
        locked: false,
    },
    {//Safe
        category: 'Safe',
        coordinates: [1833, 1128],
        iconUrl: '../images/icons/containers/safe-icon.webp',
        tooltipText: 'SAFE',
        popupText: 'Possible safe spawn',
        height: '',
        locked: false,
    },
    {//Safe
        category: 'Safe',
        coordinates: [1717, 1677],
        iconUrl: '../images/icons/containers/safe-icon.webp',
        tooltipText: 'SAFE',
        popupText: 'Possible safe spawn',
        height: 'up',
        locked: false,
    },
    {//Safe
        category: 'Safe',
        coordinates: [1759, 1604],
        iconUrl: '../images/icons/containers/safe-icon.webp',
        tooltipText: 'SAFE',
        popupText: 'Possible safe spawn',
        height: '',
        locked: false,
    },
    {//Safe
        category: 'Safe',
        coordinates: [2492, 1284],
        iconUrl: '../images/icons/containers/safe-icon.webp',
        tooltipText: 'SAFE',
        popupText: 'Possible safe spawn',
        height: 'up',
        locked: false,
    },
    {//Safe
        category: 'Safe',
        coordinates: [2638, 1195],
        iconUrl: '../images/icons/containers/safe-icon.webp',
        tooltipText: 'SAFE',
        popupText: 'Possible safe spawn',
        height: '',
        locked: false,
    },
    {//Safe
        category: 'Safe',
        coordinates: [2718, 1265],
        iconUrl: '../images/icons/containers/safe-icon.webp',
        tooltipText: 'SAFE',
        popupText: 'Possible safe spawn',
        height: 'up',
        locked: false,
    },
    {//Safe
        category: 'Safe',
        coordinates: [2716, 1337],
        iconUrl: '../images/icons/containers/safe-icon.webp',
        tooltipText: 'SAFE',
        popupText: 'Possible safe spawn',
        height: 'up',
        locked: false,
    },
    {//Safe
        category: 'Safe',
        coordinates: [2706, 1352],
        iconUrl: '../images/icons/containers/safe-icon.webp',
        tooltipText: 'SAFE',
        popupText: 'Safe behind keycard door',
        height: 'up',
        locked: true,
    },
    {//Safe
        category: 'Safe',
        coordinates: [2699, 1373],
        iconUrl: '../images/icons/containers/safe-icon.webp',
        tooltipText: 'SAFE',
        popupText: 'Safe behind keycard door',
        height: 'up',
        locked: true,
    },
    {//Safe
        category: 'Safe',
        coordinates: [2742, 2003],
        iconUrl: '../images/icons/containers/safe-icon.webp',
        tooltipText: 'SAFE',
        popupText: 'Possible safe spawn',
        height: 'up',
        locked: false,
    },
    {//Safe
        category: 'Safe',
        coordinates: [2756, 1982],
        iconUrl: '../images/icons/containers/safe-icon.webp',
        tooltipText: 'SAFE',
        popupText: 'Safe behind keycard door',
        height: 'up',
        locked: true,
    },
    {//Safe
        category: 'Safe',
        coordinates: [2791, 2027],
        iconUrl: '../images/icons/containers/safe-icon.webp',
        tooltipText: 'SAFE',
        popupText: 'Possible safe spawn',
        height: '',
        locked: false,
    },
    {//Safe
        category: 'Safe',
        coordinates: [3370, 2547],
        iconUrl: '../images/icons/containers/safe-icon.webp',
        tooltipText: 'SAFE',
        popupText: 'Possible safe spawn',
        height: '',
        locked: false,
    },
    {//Safe
        category: 'Safe',
        coordinates: [3450, 2416],
        iconUrl: '../images/icons/containers/safe-icon.webp',
        tooltipText: 'SAFE',
        popupText: 'Possible safe spawn',
        height: '',
        locked: false,
    },


    
    {//Server
        category: 'Server',
        coordinates: [1776, 1051],
        iconUrl: '../images/icons/containers/server-icon.webp',
        tooltipText: 'SERVER',
        popupText: 'Server behind keycard door',
        height: 'up',
        locked: true,
    },
    {//Server
        category: 'Server',
        coordinates: [2528, 1191],
        iconUrl: '../images/icons/containers/server-icon.webp',
        tooltipText: 'SERVER',
        popupText: 'Server behind keycard door',
        height: 'up',
        locked: true,
    },
    {//Server
        category: 'Server',
        coordinates: [2526, 1198],
        iconUrl: '../images/icons/containers/server-icon.webp',
        tooltipText: 'SERVER',
        popupText: 'Server behind keycard door',
        height: 'up',
        locked: true,
    },
    {//Server
        category: 'Server',
        coordinates: [2530, 1204],
        iconUrl: '../images/icons/containers/server-icon.webp',
        tooltipText: 'SERVER',
        popupText: 'Server',
        height: 'up',
        locked: false,
    },
    {//Server
        category: 'Server',
        coordinates: [2587, 1184],
        iconUrl: '../images/icons/containers/server-icon.webp',
        tooltipText: 'SERVER',
        popupText: 'Event loot',
        height: '',
        locked: false,
    },
    {//Server
        category: 'Server',
        coordinates: [2621, 1264],
        iconUrl: '../images/icons/containers/server-icon.webp',
        tooltipText: 'SERVER',
        popupText: 'Server',
        height: '',
        locked: false,
    },
    {//Server
        category: 'Server',
        coordinates: [2740, 2010],
        iconUrl: '../images/icons/containers/server-icon.webp',
        tooltipText: 'SERVER',
        popupText: 'Server',
        height: 'up',
        locked: false,
    },
    {//Server
        category: 'Server',
        coordinates: [2745, 2012],
        iconUrl: '../images/icons/containers/server-icon.webp',
        tooltipText: 'SERVER',
        popupText: 'Server behind keycard door',
        height: 'up',
        locked: true,
    },
    {//Server
        category: 'Server',
        coordinates: [2765, 2001],
        iconUrl: '../images/icons/containers/server-icon.webp',
        tooltipText: 'SERVER',
        popupText: 'Server behind keycard door',
        height: 'up',
        locked: true,
    },


    {//Boss
        category: 'Boss',
        coordinates: [2677, 1367],
        iconUrl: '../images/icons/boss-icon-red.webp',
        tooltipText: 'GUARD CAPTAIN SAEED',
        popupText: 'Chance for boss spawn',
        height: 'up',
        locked: false,
    },
    {//Boss
        category: 'Boss',
        coordinates: [3201, 1951],
        iconUrl: '../images/icons/boss-icon-yellow.webp',
        tooltipText: 'Mini Boss',
        popupText: 'Chance for boss spawn',
        height: 'up',
        locked: false,
    },
    {//Boss
        category: 'Boss',
        coordinates: [3194, 1218],
        iconUrl: '../images/icons/boss-icon-yellow.webp',
        tooltipText: 'Mini Boss',
        popupText: 'Chance for boss spawn',
        height: 'up',
        locked: false,
    },


    {//Elevator Extract
        category: 'Industrial Elevator',
        coordinates: [2971, 946],
        iconUrl: '../images/icons/industrial-extract-icon.webp',
        tooltipText: 'INDUSTRIAL ELEVATOR EXTRACT',
        popupText: 'Industrial Elevator Extract',
        height: '',
        locked: false,
    },
    {//Elevator Switch
        category: 'Industrial Elevator',
        coordinates: [2530, 1187],
        iconUrl: '../images/icons/event-trigger-icon.webp',
        tooltipText: 'INDUSTRIAL ELEVATOR SWITCH',
        popupText: 'Activate this switch to open the Industrial Elevator Extract',
        height: 'up',
        locked: false,
    },
    {//Elevator Switch
        category: 'Industrial Elevator',
        coordinates: [2953, 1723],
        iconUrl: '../images/icons/event-trigger-icon.webp',
        tooltipText: 'INDUSTRIAL ELEVATOR SWITCH',
        popupText: 'Activate this switch to open the Industrial Elevator Extract',
        height: '',
        locked: false,
    },
    
    {//Paid Extract
        category: 'Paid Extract',
        coordinates: [2249, 2237],
        iconUrl: '../images/icons/paid-extract-icon.webp',
        tooltipText: 'PAID EXTRACT',
        popupText: 'Pay 10,000 currency earned in-match to extract. Earn in-match currency by looting players and finishing map events.',
        height: '',
        locked: false,
    },
    {//Random Extract
        category: 'Random Extract',
        coordinates: [1500, 1989],
        iconUrl: '../images/icons/random-extract-icon.webp',
        tooltipText: 'RANDOM EXTRACT',
        popupText: 'Randomly open or closed throughout the match.',
        height: '',
        locked: false,
    },
    {//Random Extract
        category: 'Random Extract',
        coordinates: [3303, 3040],
        iconUrl: '../images/icons/random-extract-icon.webp',
        tooltipText: 'RANDOM EXTRACT',
        popupText: 'Randomly open or closed throughout the match.',
        height: '',
        locked: false,
    },
    {//Conditional Extract
        category: 'Conditional Extract',
        coordinates: [3636, 1431],
        iconUrl: '../images/icons/conditional-extract-icon.webp',
        tooltipText: 'CONDITIONAL EXTRACT',
        popupText: 'Weight limit',
        height: '',
        locked: false,
    },
    {//Conditional Extract
        category: 'Conditional Extract',
        coordinates: [1576, 908],
        iconUrl: '../images/icons/conditional-extract-icon.webp',
        tooltipText: 'CONDITIONAL EXTRACT',
        popupText: 'Extract without a backpack',
        height: '',
        locked: false,
    },
    {//Normal Extract
        category: 'Normal Extract',
        coordinates: [1255, 2000],
        iconUrl: '../images/icons/extract-icon.webp',
        tooltipText: 'NORMAL EXTRACT',
        popupText: 'Open at all times',
        height: '',
        locked: false,
    },
    {//Normal Extract
        category: 'Normal Extract',
        coordinates: [3700, 2277],
        iconUrl: '../images/icons/extract-icon.webp',
        tooltipText: 'NORMAL EXTRACT',
        popupText: 'Open at all times',
        height: '',
        locked: false,
    },


    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [1198, 1207],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [1623, 974],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [1500, 1732],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: 'up',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [1767, 1571],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [1847, 1733],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: 'up',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [1821, 2084],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [1814, 2032],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [1724, 2064],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [1725, 1987],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [2314, 1163],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [2349, 1142],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [2720, 1100],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [3009, 1387],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [3225, 1406],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [3608, 1360],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [2738, 1673],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [2935, 1711],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [3244, 1934],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },


    {//Small Safebox
        category: 'Small Safebox',
        coordinates: [2563, 2209],
        iconUrl: '../images/icons/containers/small-safebox-icon.webp',
        tooltipText: 'SMALL SAFEBOX',
        popupText: 'Small Safebox',
        height: 'up',
        locked: false,
    },
    {//Small Safebox
        category: 'Small Safebox',
        coordinates: [2708, 1323],
        iconUrl: '../images/icons/containers/small-safebox-icon.webp',
        tooltipText: 'SMALL SAFEBOX',
        popupText: 'Small Safebox',
        height: 'up',
        locked: false,
    },
    {//Small Safebox
        category: 'Small Safebox',
        coordinates: [3442, 2559],
        iconUrl: '../images/icons/containers/small-safebox-icon.webp',
        tooltipText: 'SMALL SAFEBOX',
        popupText: 'Small Safebox',
        height: '',
        locked: true,
    },

    
    {//Computer Case
        category: 'Computer Case',
        coordinates: [1785, 1064],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Computer Case',
        height: '',
        locked: true,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [1584, 1723],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Computer Case locked behind keycard door',
        height: 'up',
        locked: true,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [1793, 1826],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Computer Case locked behind keycard door',
        height: '',
        locked: true,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [1802, 1844],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Computer Case',
        height: '',
        locked: false,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [2868, 894],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Computer Case',
        height: '',
        locked: false,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [2567, 2207],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Computer Case',
        height: '',
        locked: false,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [3340, 2547],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Computer Case',
        height: '',
        locked: false,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [3341, 2480],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Event loot',
        height: '',
        locked: false,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [3346, 2482],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Event loot',
        height: '',
        locked: false,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [2571, 1197],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Computer Case',
        height: '',
        locked: false,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [2579, 1202],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Event loot',
        height: '',
        locked: false,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [2583, 1203],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Event loot',
        height: '',
        locked: false,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [2519, 1276],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Computer case',
        height: '',
        locked: false,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [2551, 1264],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Computer case',
        height: '',
        locked: true,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [2544, 1274],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Computer case',
        height: '',
        locked: true,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [2555, 1282],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Computer case',
        height: '',
        locked: true,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [2783, 1257],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Computer case',
        height: '',
        locked: false,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [2760, 1312],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Computer case',
        height: '',
        locked: true,
    },

    
    {//LG Weapon Crate
        category: 'LG Weapon Crate',
        coordinates: [1750, 1610],
        iconUrl: '../images/icons/containers/large-weapon-crate-icon.webp',
        tooltipText: 'LARGE WEAPON CRATE',
        popupText: 'Large Weapon Crate',
        height: 'up',
        locked: false,
    },
    {//LG Weapon Crate
        category: 'LG Weapon Crate',
        coordinates: [1716, 1761],
        iconUrl: '../images/icons/containers/large-weapon-crate-icon.webp',
        tooltipText: 'LARGE WEAPON CRATE',
        popupText: 'Large Weapon Crate',
        height: 'up',
        locked: false,
    },
    {//LG Weapon Crate
        category: 'LG Weapon Crate',
        coordinates: [3334, 2486],
        iconUrl: '../images/icons/containers/large-weapon-crate-icon.webp',
        tooltipText: 'LARGE WEAPON CRATE',
        popupText: 'Event loot',
        height: '',
        locked: false,
    },
    {//LG Weapon Crate
        category: 'LG Weapon Crate',
        coordinates: [2926, 1332],
        iconUrl: '../images/icons/containers/large-weapon-crate-icon.webp',
        tooltipText: 'LARGE WEAPON CRATE',
        popupText: 'Large Weapon Crate',
        height: 'up',
        locked: false,
    },
    {//LG Weapon Crate
        category: 'LG Weapon Crate',
        coordinates: [2561, 825],
        iconUrl: '../images/icons/containers/large-weapon-crate-icon.webp',
        tooltipText: 'LARGE WEAPON CRATE',
        popupText: 'Large Weapon Crate',
        height: '',
        locked: false,
    },
    {//LG Weapon Crate
        category: 'LG Weapon Crate',
        coordinates: [2522, 1033],
        iconUrl: '../images/icons/containers/large-weapon-crate-icon.webp',
        tooltipText: 'LARGE WEAPON CRATE',
        popupText: 'Large Weapon Crate',
        height: 'up',
        locked: false,
    },
    {//LG Weapon Crate
        category: 'LG Weapon Crate',
        coordinates: [2805, 1118],
        iconUrl: '../images/icons/containers/large-weapon-crate-icon.webp',
        tooltipText: 'LARGE WEAPON CRATE',
        popupText: 'Large Weapon Crate',
        height: 'up',
        locked: false,
    },
    {//LG Weapon Crate
        category: 'LG Weapon Crate',
        coordinates: [2541, 1162],
        iconUrl: '../images/icons/containers/large-weapon-crate-icon.webp',
        tooltipText: 'LARGE WEAPON CRATE',
        popupText: 'Large Weapon Crate',
        height: '',
        locked: false,
    },
    {//LG Weapon Crate
        category: 'LG Weapon Crate',
        coordinates: [2579, 1197],
        iconUrl: '../images/icons/containers/large-weapon-crate-icon.webp',
        tooltipText: 'LARGE WEAPON CRATE',
        popupText: 'Event loot',
        height: '',
        locked: false,
    },
    {//LG Weapon Crate
        category: 'LG Weapon Crate',
        coordinates: [2627, 1370],
        iconUrl: '../images/icons/containers/large-weapon-crate-icon.webp',
        tooltipText: 'LARGE WEAPON CRATE',
        popupText: 'Large Weapon Crate',
        height: 'up',
        locked: false,
    },
    {//LG Weapon Crate
        category: 'LG Weapon Crate',
        coordinates: [2665, 1357],
        iconUrl: '../images/icons/containers/large-weapon-crate-icon.webp',
        tooltipText: 'LARGE WEAPON CRATE',
        popupText: 'Large Weapon Crate',
        height: 'up',
        locked: true,
    },

    
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [1759, 1193],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [1900, 1180],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [1964, 1010],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [1355, 1832],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [2323, 1168],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [2452, 1141],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [2424, 1279],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [2800, 1201],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [3000, 1471],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [2739, 1973],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [3167, 2000],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [2855, 2390],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [3344, 2198],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },

    
    {//Tool Cabinet
        category: 'Tool Cabinet',
        coordinates: [1311, 1212],
        iconUrl: '../images/icons/containers/tool-cabinet-icon.webp',
        tooltipText: 'TOOL CABINET',
        popupText: 'Tool Cabinet',
        height: 'up',
        locked: false,
    },
    {//Tool Cabinet
        category: 'Tool Cabinet',
        coordinates: [1778, 1505],
        iconUrl: '../images/icons/containers/tool-cabinet-icon.webp',
        tooltipText: 'TOOL CABINET',
        popupText: 'Tool Cabinet',
        height: '',
        locked: false,
    },
    {//Tool Cabinet
        category: 'Tool Cabinet',
        coordinates: [1732, 1558],
        iconUrl: '../images/icons/containers/tool-cabinet-icon.webp',
        tooltipText: 'TOOL CABINET',
        popupText: 'Tool Cabinet',
        height: 'up',
        locked: false,
    },
    {//Tool Cabinet
        category: 'Tool Cabinet',
        coordinates: [1750, 1617],
        iconUrl: '../images/icons/containers/tool-cabinet-icon.webp',
        tooltipText: 'TOOL CABINET',
        popupText: 'Tool Cabinet',
        height: '',
        locked: false,
    },
    {//Tool Cabinet
        category: 'Tool Cabinet',
        coordinates: [1853, 1763],
        iconUrl: '../images/icons/containers/tool-cabinet-icon.webp',
        tooltipText: 'TOOL CABINET',
        popupText: 'Tool Cabinet',
        height: 'up',
        locked: false,
    },
    {//Tool Cabinet
        category: 'Tool Cabinet',
        coordinates: [2662, 821],
        iconUrl: '../images/icons/containers/tool-cabinet-icon.webp',
        tooltipText: 'TOOL CABINET',
        popupText: 'Tool Cabinet',
        height: '',
        locked: false,
    },
    {//Tool Cabinet
        category: 'Tool Cabinet',
        coordinates: [2457, 1134],
        iconUrl: '../images/icons/containers/tool-cabinet-icon.webp',
        tooltipText: 'TOOL CABINET',
        popupText: 'Tool Cabinet',
        height: '',
        locked: false,
    },
    {//Tool Cabinet
        category: 'Tool Cabinet',
        coordinates: [2489, 1150],
        iconUrl: '../images/icons/containers/tool-cabinet-icon.webp',
        tooltipText: 'TOOL CABINET',
        popupText: 'Tool Cabinet',
        height: '',
        locked: false,
    },
    {//Tool Cabinet
        category: 'Tool Cabinet',
        coordinates: [2447, 1247],
        iconUrl: '../images/icons/containers/tool-cabinet-icon.webp',
        tooltipText: 'TOOL CABINET',
        popupText: 'Tool Cabinet',
        height: '',
        locked: false,
    },
    {//Tool Cabinet
        category: 'Tool Cabinet',
        coordinates: [2526, 1129],
        iconUrl: '../images/icons/containers/tool-cabinet-icon.webp',
        tooltipText: 'TOOL CABINET',
        popupText: 'Tool Cabinet',
        height: '',
        locked: false,
    },
    {//Tool Cabinet
        category: 'Tool Cabinet',
        coordinates: [2557, 1149],
        iconUrl: '../images/icons/containers/tool-cabinet-icon.webp',
        tooltipText: 'TOOL CABINET',
        popupText: 'Tool Cabinet',
        height: '',
        locked: false,
    },
    {//Tool Cabinet
        category: 'Tool Cabinet',
        coordinates: [2630, 1214],
        iconUrl: '../images/icons/containers/tool-cabinet-icon.webp',
        tooltipText: 'TOOL CABINET',
        popupText: 'Tool Cabinet',
        height: '',
        locked: false,
    },
    {//Tool Cabinet
        category: 'Tool Cabinet',
        coordinates: [3021, 1367],
        iconUrl: '../images/icons/containers/tool-cabinet-icon.webp',
        tooltipText: 'TOOL CABINET',
        popupText: 'Tool Cabinet',
        height: '',
        locked: false,
    },
    {//Tool Cabinet
        category: 'Tool Cabinet',
        coordinates: [2681, 1943],
        iconUrl: '../images/icons/containers/tool-cabinet-icon.webp',
        tooltipText: 'TOOL CABINET',
        popupText: 'Tool Cabinet',
        height: '',
        locked: false,
    },
    {//Tool Cabinet
        category: 'Tool Cabinet',
        coordinates: [2849, 1973],
        iconUrl: '../images/icons/containers/tool-cabinet-icon.webp',
        tooltipText: 'TOOL CABINET',
        popupText: 'Tool Cabinet',
        height: '',
        locked: false,
    },
    {//Tool Cabinet
        category: 'Tool Cabinet',
        coordinates: [2841, 2034],
        iconUrl: '../images/icons/containers/tool-cabinet-icon.webp',
        tooltipText: 'TOOL CABINET',
        popupText: 'Tool Cabinet',
        height: '',
        locked: false,
    },
    {//Tool Cabinet
        category: 'Tool Cabinet',
        coordinates: [3115, 2174],
        iconUrl: '../images/icons/containers/tool-cabinet-icon.webp',
        tooltipText: 'TOOL CABINET',
        popupText: 'Tool Cabinet',
        height: 'down',
        locked: false,
    },

    
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [1234, 1266],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'LG Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [1360, 1156],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'LG Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [1510, 1065],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'LG Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [1476, 1065],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'LG Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [1430, 1874],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'LG Tool Box',
        height: 'down',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [1951, 2015],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'LG Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [2512, 1149],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'LG Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [2498, 1242],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'LG Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [2682, 1080],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'LG Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [2816, 877],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'LG Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [2761, 912],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'LG Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [3014, 1094],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'LG Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [2994, 1331],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'LG Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [2919, 1366],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'LG Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [3156, 1400],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'LG Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [2934, 1736],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'LG Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [2737, 1990],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'LG Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [2525, 2125],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'LG Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [2509, 2218],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'LG Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [2863, 2332],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'LG Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [3033, 1933],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'LG Tool Box',
        height: '',
        locked: false,
    },


    {//Lab Coat
        category: 'Lab Coat',
        coordinates: [1908, 1508],
        iconUrl: '../images/icons/containers/lab-coat-icon.webp',
        tooltipText: 'LAB COAT',
        popupText: 'Lab Coat locked behind keycard door',
        height: '',
        locked: true,
    },
    {//Lab Coat
        category: 'Lab Coat',
        coordinates: [1921, 1503],
        iconUrl: '../images/icons/containers/lab-coat-icon.webp',
        tooltipText: 'LAB COAT',
        popupText: 'Lab Coat locked behind keycard door',
        height: '',
        locked: true,
    },
    {//Lab Coat
        category: 'Lab Coat',
        coordinates: [2520, 1187],
        iconUrl: '../images/icons/containers/lab-coat-icon.webp',
        tooltipText: 'LAB COAT',
        popupText: 'Lab Coat behind keycard door',
        height: 'up',
        locked: true,
    },
    {//Lab Coat
        category: 'Lab Coat',
        coordinates: [2565, 1193],
        iconUrl: '../images/icons/containers/lab-coat-icon.webp',
        tooltipText: 'LAB COAT',
        popupText: 'Lab Coat',
        height: '',
        locked: false,
    },
    {//Lab Coat
        category: 'Lab Coat',
        coordinates: [2566, 1187],
        iconUrl: '../images/icons/containers/lab-coat-icon.webp',
        tooltipText: 'LAB COAT',
        popupText: 'Lab Coat',
        height: '',
        locked: false,
    },
    {//Lab Coat
        category: 'Lab Coat',
        coordinates: [2559, 1280],
        iconUrl: '../images/icons/containers/lab-coat-icon.webp',
        tooltipText: 'LAB COAT',
        popupText: 'Lab Coat',
        height: '',
        locked: false,
    },
    {//Lab Coat
        category: 'Lab Coat',
        coordinates: [2753, 1277],
        iconUrl: '../images/icons/containers/lab-coat-icon.webp',
        tooltipText: 'LAB COAT',
        popupText: 'Lab Coat',
        height: '',
        locked: false,
    },
    {//Lab Coat
        category: 'Lab Coat',
        coordinates: [2735, 1346],
        iconUrl: '../images/icons/containers/lab-coat-icon.webp',
        tooltipText: 'LAB COAT',
        popupText: 'Lab Coat',
        height: '',
        locked: false,
    },
    {//Lab Coat
        category: 'Lab Coat',
        coordinates: [2729, 2029],
        iconUrl: '../images/icons/containers/lab-coat-icon.webp',
        tooltipText: 'LAB COAT',
        popupText: 'Lab Coat',
        height: '',
        locked: false,
    },
    {//Lab Coat
        category: 'Lab Coat',
        coordinates: [2755, 2031],
        iconUrl: '../images/icons/containers/lab-coat-icon.webp',
        tooltipText: 'LAB COAT',
        popupText: 'Lab Coat',
        height: '',
        locked: false,
    },
    {//Lab Coat
        category: 'Lab Coat',
        coordinates: [2756, 2024],
        iconUrl: '../images/icons/containers/lab-coat-icon.webp',
        tooltipText: 'LAB COAT',
        popupText: 'Lab Coat',
        height: '',
        locked: false,
    },


    {//Clothing
        category: 'Clothing',
        coordinates: [1577, 1715],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing locked behind keycard door',
        height: 'up',
        locked: true,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [1784, 1833],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing locked behind keycard door',
        height: '',
        locked: true,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [1816, 1844],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [2070, 1231],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [2590, 1049],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [2681, 1084],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [2813, 1150],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [2552, 2222],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Event loot',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [2942, 1721],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [3564, 1375],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [3359, 1799],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },


    {//Military Medkit
        category: 'Military Medkit',
        coordinates: [1372, 1859],
        iconUrl: '../images/icons/containers/military-med-kit-icon.webp',
        tooltipText: 'MILITARY MEDKIT',
        popupText: 'Military Medkit',
        height: '',
        locked: false,
    },
    {//Military Medkit
        category: 'Military Medkit',
        coordinates: [1853, 1133],
        iconUrl: '../images/icons/containers/military-med-kit-icon.webp',
        tooltipText: 'MILITARY MEDKIT',
        popupText: 'Military Medkit',
        height: '',
        locked: false,
    },
    {//Military Medkit
        category: 'Military Medkit',
        coordinates: [2565, 1303],
        iconUrl: '../images/icons/containers/military-med-kit-icon.webp',
        tooltipText: 'MILITARY MEDKIT',
        popupText: 'Military Medkit',
        height: '',
        locked: false,
    },
    {//Military Medkit
        category: 'Military Medkit',
        coordinates: [2563, 1284],
        iconUrl: '../images/icons/containers/military-med-kit-icon.webp',
        tooltipText: 'MILITARY MEDKIT',
        popupText: 'Military Medkit',
        height: '',
        locked: false,
    },
    {//Military Medkit
        category: 'Military Medkit',
        coordinates: [2714, 1257],
        iconUrl: '../images/icons/containers/military-med-kit-icon.webp',
        tooltipText: 'MILITARY MEDKIT',
        popupText: 'Military Medkit',
        height: '',
        locked: false,
    },
    {//Military Medkit
        category: 'Military Medkit',
        coordinates: [2931, 2286],
        iconUrl: '../images/icons/containers/military-med-kit-icon.webp',
        tooltipText: 'MILITARY MEDKIT',
        popupText: 'Military Medkit',
        height: '',
        locked: false,
    },
    {//Military Medkit
        category: 'Military Medkit',
        coordinates: [3365, 1780],
        iconUrl: '../images/icons/containers/military-med-kit-icon.webp',
        tooltipText: 'MILITARY MEDKIT',
        popupText: 'Military Medkit',
        height: '',
        locked: false,
    },
    {//Military Medkit
        category: 'Military Medkit',
        coordinates: [3540, 2165],
        iconUrl: '../images/icons/containers/military-med-kit-icon.webp',
        tooltipText: 'MILITARY MEDKIT',
        popupText: 'Military Medkit',
        height: '',
        locked: false,
    },
    {//Military Medkit
        category: 'Military Medkit',
        coordinates: [3501, 2412],
        iconUrl: '../images/icons/containers/military-med-kit-icon.webp',
        tooltipText: 'MILITARY MEDKIT',
        popupText: 'Military Medkit',
        height: '',
        locked: false,
    },


    {//Medical Pile
        category: 'Medical Pile',
        coordinates: [2853, 1715],
        iconUrl: '../images/icons/containers/pile-of-medical-supplies-icon.webp',
        tooltipText: 'MEDICAL PILE',
        popupText: 'Pile of medical supplies',
        height: '',
        locked: false,
    },
    {//Medical Pile
        category: 'Medical Pile',
        coordinates: [2851, 1128],
        iconUrl: '../images/icons/containers/pile-of-medical-supplies-icon.webp',
        tooltipText: 'MEDICAL PILE',
        popupText: 'Pile of medical supplies',
        height: '',
        locked: false,
    },
    {//Medical Pile
        category: 'Medical Pile',
        coordinates: [2639, 1063],
        iconUrl: '../images/icons/containers/pile-of-medical-supplies-icon.webp',
        tooltipText: 'MEDICAL PILE',
        popupText: 'Pile of medical supplies',
        height: '',
        locked: false,
    },
    {//Medical Pile
        category: 'Medical Pile',
        coordinates: [2137, 1195],
        iconUrl: '../images/icons/containers/pile-of-medical-supplies-icon.webp',
        tooltipText: 'MEDICAL PILE',
        popupText: 'Pile of medical supplies',
        height: '',
        locked: false,
    },
    {//Medical Pile
        category: 'Medical Pile',
        coordinates: [1138, 1569],
        iconUrl: '../images/icons/containers/pile-of-medical-supplies-icon.webp',
        tooltipText: 'MEDICAL PILE',
        popupText: 'Pile of medical supplies',
        height: '',
        locked: false,
    },


    {//Briefcase
        category: 'Briefcase',
        coordinates: [2574, 1175],
        iconUrl: '../images/icons/containers/briefcase-icon.webp',
        tooltipText: 'BRIEFCASE',
        popupText: 'Briefcase',
        height: '',
        locked: false,
    },
    {//Briefcase
        category: 'Briefcase',
        coordinates: [2697, 1322],
        iconUrl: '../images/icons/containers/briefcase-icon.webp',
        tooltipText: 'BRIEFCASE',
        popupText: 'Briefcase',
        height: '',
        locked: false,
    },
    {//Briefcase
        category: 'Briefcase',
        coordinates: [2706, 1343],
        iconUrl: '../images/icons/containers/briefcase-icon.webp',
        tooltipText: 'BRIEFCASE',
        popupText: 'Briefcase',
        height: '',
        locked: false,
    },
    {//Briefcase
        category: 'Briefcase',
        coordinates: [2700, 1370],
        iconUrl: '../images/icons/containers/briefcase-icon.webp',
        tooltipText: 'BRIEFCASE',
        popupText: 'Briefcase',
        height: '',
        locked: false,
    },
    {//Briefcase
        category: 'Briefcase',
        coordinates: [2680, 1354],
        iconUrl: '../images/icons/containers/briefcase-icon.webp',
        tooltipText: 'BRIEFCASE',
        popupText: 'Briefcase',
        height: '',
        locked: false,
    },
    {//Briefcase
        category: 'Briefcase',
        coordinates: [3484, 2360],
        iconUrl: '../images/icons/containers/briefcase-icon.webp',
        tooltipText: 'BRIEFCASE',
        popupText: 'Briefcase',
        height: '',
        locked: false,
    },
    {//Briefcase
        category: 'Briefcase',
        coordinates: [3481, 2432],
        iconUrl: '../images/icons/containers/briefcase-icon.webp',
        tooltipText: 'BRIEFCASE',
        popupText: 'Briefcase',
        height: '',
        locked: false,
    },
    {//Briefcase
        category: 'Briefcase',
        coordinates: [3447, 2528],
        iconUrl: '../images/icons/containers/briefcase-icon.webp',
        tooltipText: 'BRIEFCASE',
        popupText: 'Briefcase',
        height: '',
        locked: false,
    },


    {//Premium Storage
        category: 'Premium Storage',
        coordinates: [2612, 1074],
        iconUrl: '../images/icons/containers/premium-storage-box-icon.webp',
        tooltipText: 'PREMIUM STORAGE BOX',
        popupText: 'Premium Storage Box',
        height: '',
        locked: false,
    },
    {//Premium Storage
        category: 'Premium Storage',
        coordinates: [2718, 1378],
        iconUrl: '../images/icons/containers/premium-storage-box-icon.webp',
        tooltipText: 'PREMIUM STORAGE BOX',
        popupText: 'Premium Storage Box',
        height: '',
        locked: false,
    },

    
    {//Drawers
        category: 'Drawers',
        coordinates: [2681, 1369],
        iconUrl: '../images/icons/containers/drawer-icon.webp',
        tooltipText: 'DRAWERS',
        popupText: 'Drawers',
        height: '',
        locked: false,
    },
    {//Drawers
        category: 'Drawers',
        coordinates: [2758, 1282],
        iconUrl: '../images/icons/containers/drawer-icon.webp',
        tooltipText: 'DRAWERS',
        popupText: 'Drawers inside locked room. Unlock room with the computer by the door.',
        height: 'up',
        locked: true,
    },
    {//Drawers
        category: 'Drawers',
        coordinates: [1563, 1625],
        iconUrl: '../images/icons/containers/drawer-icon.webp',
        tooltipText: 'DRAWERS',
        popupText: 'Drawers',
        height: '',
        locked: false,
    },
    {//Drawers
        category: 'Drawers',
        coordinates: [3342, 2468],
        iconUrl: '../images/icons/containers/drawer-icon.webp',
        tooltipText: 'DRAWERS',
        popupText: 'Drawers',
        height: '',
        locked: false,
    },


    {//Mountaineering Bag
        category: 'Premium Storage',
        coordinates: [1912, 1503],
        iconUrl: '../images/icons/containers/premium-storage-box-icon.webp',
        tooltipText: 'MOUNTAINEERING BAG',
        popupText: 'No info (msg me if you have details, locked behind keycard door)',
        height: '',
        locked: true,
    },

    
    {//Courier Carton
        category: 'Courier Carton',
        coordinates: [1775, 1072],
        iconUrl: '../images/icons/containers/courier-carton-icon.webp',
        tooltipText: 'COURIER CARTON',
        popupText: 'Courier Carton',
        height: '',
        locked: false,
    },
    {//Courier Carton
        category: 'Courier Carton',
        coordinates: [2724, 1109],
        iconUrl: '../images/icons/containers/courier-carton-icon.webp',
        tooltipText: 'COURIER CARTON',
        popupText: 'Courier Carton',
        height: '',
        locked: false,
    },
    {//Courier Carton
        category: 'Courier Carton',
        coordinates: [2687, 1386],
        iconUrl: '../images/icons/containers/courier-carton-icon.webp',
        tooltipText: 'COURIER CARTON',
        popupText: 'Courier Carton',
        height: '',
        locked: false,
    },
    {//Courier Carton
        category: 'Courier Carton',
        coordinates: [2571, 2210],
        iconUrl: '../images/icons/containers/courier-carton-icon.webp',
        tooltipText: 'COURIER CARTON',
        popupText: 'Courier Carton',
        height: '',
        locked: false,
    },
    {//Courier Carton
        category: 'Courier Carton',
        coordinates: [3044, 1862],
        iconUrl: '../images/icons/containers/courier-carton-icon.webp',
        tooltipText: 'COURIER CARTON',
        popupText: 'Courier Carton',
        height: 'down',
        locked: false,
    },


    {//Flight Case
        category: 'Flight Case',
        coordinates: [1735, 1672],
        iconUrl: '../images/icons/containers/flight-case-icon.webp',
        tooltipText: 'FLIGHT CASE',
        popupText: 'Flight Case',
        height: 'up',
        locked: false,
    },
    {//Flight Case
        category: 'Flight Case',
        coordinates: [1703, 1731],
        iconUrl: '../images/icons/containers/flight-case-icon.webp',
        tooltipText: 'FLIGHT CASE',
        popupText: 'Flight Case',
        height: '',
        locked: false,
    },
    {//Flight Case
        category: 'Flight Case',
        coordinates: [2603, 1059],
        iconUrl: '../images/icons/containers/flight-case-icon.webp',
        tooltipText: 'FLIGHT CASE',
        popupText: 'Flight Case',
        height: '',
        locked: false,
    },
    {//Flight Case
        category: 'Flight Case',
        coordinates: [2723, 1092],
        iconUrl: '../images/icons/containers/flight-case-icon.webp',
        tooltipText: 'FLIGHT CASE',
        popupText: 'Flight Case',
        height: '',
        locked: false,
    },
    {//Flight Case
        category: 'Flight Case',
        coordinates: [2968, 1365],
        iconUrl: '../images/icons/containers/flight-case-icon.webp',
        tooltipText: 'FLIGHT CASE',
        popupText: 'Flight Case',
        height: '',
        locked: false,
    },
    {//Flight Case
        category: 'Flight Case',
        coordinates: [2514, 2137],
        iconUrl: '../images/icons/containers/flight-case-icon.webp',
        tooltipText: 'FLIGHT CASE',
        popupText: 'Flight Case',
        height: '',
        locked: false,
    },


    {//Dumpster
        category: 'Dumpster',
        coordinates: [2090, 1175],
        iconUrl: '../images/icons/containers/dumpster-icon.webp',
        tooltipText: 'DUMPSTER',
        popupText: 'Dumpster',
        height: '',
        locked: false,
    },
    {//Dumpster
        category: 'Dumpster',
        coordinates: [2452, 936],
        iconUrl: '../images/icons/containers/dumpster-icon.webp',
        tooltipText: 'DUMPSTER',
        popupText: 'Dumpster',
        height: '',
        locked: false,
    },
    {//Dumpster
        category: 'Dumpster',
        coordinates: [3075, 1210],
        iconUrl: '../images/icons/containers/dumpster-icon.webp',
        tooltipText: 'DUMPSTER',
        popupText: 'Dumpster',
        height: '',
        locked: false,
    },
    {//Dumpster
        category: 'Dumpster',
        coordinates: [3262, 1961],
        iconUrl: '../images/icons/containers/dumpster-icon.webp',
        tooltipText: 'DUMPSTER',
        popupText: 'Dumpster',
        height: '',
        locked: false,
    },
    {//Dumpster
        category: 'Dumpster',
        coordinates: [2446, 2136],
        iconUrl: '../images/icons/containers/dumpster-icon.webp',
        tooltipText: 'DUMPSTER',
        popupText: 'Dumpster',
        height: '',
        locked: false,
    },


    {//Field Supply Box
        category: 'Field Supply',
        coordinates: [1444, 1702],
        iconUrl: '../images/icons/containers/field-supply-box-icon.webp',
        tooltipText: 'FIELD SUPPLY BOX',
        popupText: 'Field Supply Box',
        height: '',
        locked: false,
    },
    {//Field Supply Box
        category: 'Field Supply',
        coordinates: [2007, 1902],
        iconUrl: '../images/icons/containers/field-supply-box-icon.webp',
        tooltipText: 'FIELD SUPPLY BOX',
        popupText: 'Field Supply Box',
        height: '',
        locked: false,
    },
    {//Field Supply Box
        category: 'Field Supply',
        coordinates: [2107, 1943],
        iconUrl: '../images/icons/containers/field-supply-box-icon.webp',
        tooltipText: 'FIELD SUPPLY BOX',
        popupText: 'Field Supply Box',
        height: '',
        locked: false,
    },
    {//Field Supply Box
        category: 'Field Supply',
        coordinates: [2177, 2075],
        iconUrl: '../images/icons/containers/field-supply-box-icon.webp',
        tooltipText: 'FIELD SUPPLY BOX',
        popupText: 'Field Supply Box',
        height: '',
        locked: false,
    },
    {//Field Supply Box
        category: 'Field Supply',
        coordinates: [2090, 2224],
        iconUrl: '../images/icons/containers/field-supply-box-icon.webp',
        tooltipText: 'FIELD SUPPLY BOX',
        popupText: 'Field Supply Box',
        height: '',
        locked: false,
    },
    {//Field Supply Box
        category: 'Field Supply',
        coordinates: [2271, 1133],
        iconUrl: '../images/icons/containers/field-supply-box-icon.webp',
        tooltipText: 'FIELD SUPPLY BOX',
        popupText: 'Field Supply Box',
        height: '',
        locked: false,
    },
    {//Field Supply Box
        category: 'Field Supply',
        coordinates: [2528, 1555],
        iconUrl: '../images/icons/containers/field-supply-box-icon.webp',
        tooltipText: 'FIELD SUPPLY BOX',
        popupText: 'Field Supply Box',
        height: '',
        locked: false,
    },
    {//Field Supply Box
        category: 'Field Supply',
        coordinates: [2847, 1155],
        iconUrl: '../images/icons/containers/field-supply-box-icon.webp',
        tooltipText: 'FIELD SUPPLY BOX',
        popupText: 'Field Supply Box',
        height: '',
        locked: false,
    },
    {//Field Supply Box
        category: 'Field Supply',
        coordinates: [2911, 1371],
        iconUrl: '../images/icons/containers/field-supply-box-icon.webp',
        tooltipText: 'FIELD SUPPLY BOX',
        popupText: 'Field Supply Box',
        height: '',
        locked: false,
    },
    {//Field Supply Box
        category: 'Field Supply',
        coordinates: [3123, 2221],
        iconUrl: '../images/icons/containers/field-supply-box-icon.webp',
        tooltipText: 'FIELD SUPPLY BOX',
        popupText: 'Field Supply Box',
        height: '',
        locked: false,
    },
    {//Field Supply Box
        category: 'Field Supply',
        coordinates: [3002, 1891],
        iconUrl: '../images/icons/containers/field-supply-box-icon.webp',
        tooltipText: 'FIELD SUPPLY BOX',
        popupText: 'Field Supply Box',
        height: '',
        locked: false,
    },
    {//Field Supply Box
        category: 'Field Supply',
        coordinates: [2976, 1159],
        iconUrl: '../images/icons/containers/field-supply-box-icon.webp',
        tooltipText: 'FIELD SUPPLY BOX',
        popupText: 'Field Supply Box',
        height: '',
        locked: false,
    },


    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [1323, 1612],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: '',
        locked: false,
    },
    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [1385, 1778],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: '',
        locked: false,
    },
    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [1473, 1968],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: '',
        locked: false,
    },
    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [1510, 1934],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: '',
        locked: false,
    },
    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [1549, 1886],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: '',
        locked: false,
    },
    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [1825, 2037],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: '',
        locked: false,
    },
    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [2202, 1970],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: 'up',
        locked: false,
    },
    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [1725, 1757],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: 'up',
        locked: false,
    },
    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [2320, 2130],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: '',
        locked: false,
    },
    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [2385, 2096],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: '',
        locked: false,
    },
    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [2266, 1165],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: '',
        locked: false,
    },
    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [2361, 1162],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: '',
        locked: false,
    },
    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [2621, 1070],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: '',
        locked: false,
    },
    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [2827, 1158],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: '',
        locked: false,
    },
    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [2791, 1267],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: '',
        locked: false,
    },
    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [2396, 1414],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: '',
        locked: false,
    },
    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [3118, 1358],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: '',
        locked: false,
    },
    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [3217, 1201],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: '',
        locked: false,
    },
    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [3276, 1287],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: '',
        locked: false,
    },
    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [3178, 2021],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: '',
        locked: false,
    },
    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [3372, 2238],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: '',
        locked: false,
    },
    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [3355, 1819],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: '',
        locked: false,
    },

    
    {//Stash
        category: 'Stash',
        coordinates: [1786, 1465],
        iconUrl: '../images/icons/containers/hidden-stash-icon.webp',
        tooltipText: 'STASH',
        popupText: 'Stash',
        height: '',
        locked: false,
    },
    {//Stash
        category: 'Stash',
        coordinates: [2268, 1085],
        iconUrl: '../images/icons/containers/hidden-stash-icon.webp',
        tooltipText: 'STASH',
        popupText: 'Stash',
        height: '',
        locked: false,
    },
    {//Stash
        category: 'Stash',
        coordinates: [2383, 1012],
        iconUrl: '../images/icons/containers/hidden-stash-icon.webp',
        tooltipText: 'STASH',
        popupText: 'Stash',
        height: '',
        locked: false,
    },
    {//Stash
        category: 'Stash',
        coordinates: [2333, 1293],
        iconUrl: '../images/icons/containers/hidden-stash-icon.webp',
        tooltipText: 'STASH',
        popupText: 'Stash',
        height: '',
        locked: false,
    },
    {//Stash
        category: 'Stash',
        coordinates: [2807, 1386],
        iconUrl: '../images/icons/containers/hidden-stash-icon.webp',
        tooltipText: 'STASH',
        popupText: 'Stash',
        height: '',
        locked: false,
    },
    {//Stash
        category: 'Stash',
        coordinates: [2693, 1153],
        iconUrl: '../images/icons/containers/hidden-stash-icon.webp',
        tooltipText: 'STASH',
        popupText: 'Stash',
        height: '',
        locked: false,
    },
    {//Stash
        category: 'Stash',
        coordinates: [3057, 1454],
        iconUrl: '../images/icons/containers/hidden-stash-icon.webp',
        tooltipText: 'STASH',
        popupText: 'Stash',
        height: '',
        locked: false,
    },
    {//Stash
        category: 'Stash',
        coordinates: [3483, 2181],
        iconUrl: '../images/icons/containers/hidden-stash-icon.webp',
        tooltipText: 'STASH',
        popupText: 'Stash',
        height: '',
        locked: false,
    },
    {//Stash
        category: 'Stash',
        coordinates: [3269, 2408],
        iconUrl: '../images/icons/containers/hidden-stash-icon.webp',
        tooltipText: 'STASH',
        popupText: 'Stash',
        height: '',
        locked: false,
    },
    {//Stash
        category: 'Stash',
        coordinates: [3295, 2605],
        iconUrl: '../images/icons/containers/hidden-stash-icon.webp',
        tooltipText: 'STASH',
        popupText: 'Stash',
        height: '',
        locked: false,
    },


    {//Suitcase
        category: 'Suitcase',
        coordinates: [1561, 1726],
        iconUrl: '../images/icons/containers/suitcase-icon.webp',
        tooltipText: 'SUITCASE',
        popupText: 'Suitcase locked behind keycard door',
        height: 'up',
        locked: true,
    },
    {//Suitcase
        category: 'Suitcase',
        coordinates: [3463, 2428],
        iconUrl: '../images/icons/containers/suitcase-icon.webp',
        tooltipText: 'SUITCASE',
        popupText: 'Suitcase',
        height: '',
        locked: false,
    },
    {//Suitcase
        category: 'Suitcase',
        coordinates: [3371, 2465],
        iconUrl: '../images/icons/containers/suitcase-icon.webp',
        tooltipText: 'SUITCASE',
        popupText: 'Suitcase',
        height: '',
        locked: false,
    },
    {//Suitcase
        category: 'Suitcase',
        coordinates: [3428, 2490],
        iconUrl: '../images/icons/containers/suitcase-icon.webp',
        tooltipText: 'SUITCASE',
        popupText: 'Suitcase',
        height: '',
        locked: false,
    },
    {//Suitcase
        category: 'Suitcase',
        coordinates: [3442, 2549],
        iconUrl: '../images/icons/containers/suitcase-icon.webp',
        tooltipText: 'SUITCASE',
        popupText: 'Suitcase',
        height: '',
        locked: false,
    },


    
    {//Player Spawn
        category: 'Spawn',
        coordinates: [1234, 1982],
        iconUrl: '../images/icons/spawn-point-icon.webp',
        tooltipText: 'SPAWN',
        popupText: 'Player spawn',
        height: '',
        locked: false,
    },
    {//Player Spawn
        category: 'Spawn',
        coordinates: [1289, 1346],
        iconUrl: '../images/icons/spawn-point-icon.webp',
        tooltipText: 'SPAWN',
        popupText: 'Player spawn',
        height: '',
        locked: false,
    },
    {//Player Spawn
        category: 'Spawn',
        coordinates: [1352, 1132],
        iconUrl: '../images/icons/spawn-point-icon.webp',
        tooltipText: 'SPAWN',
        popupText: 'Player spawn',
        height: '',
        locked: false,
    },
    {//Player Spawn
        category: 'Spawn',
        coordinates: [1975, 1007],
        iconUrl: '../images/icons/spawn-point-icon.webp',
        tooltipText: 'SPAWN',
        popupText: 'Player spawn',
        height: '',
        locked: false,
    },
    {//Player Spawn
        category: 'Spawn',
        coordinates: [1933, 1248],
        iconUrl: '../images/icons/spawn-point-icon.webp',
        tooltipText: 'SPAWN',
        popupText: 'Player spawn',
        height: '',
        locked: false,
    },
    {//Player Spawn
        category: 'Spawn',
        coordinates: [1588, 1691],
        iconUrl: '../images/icons/spawn-point-icon.webp',
        tooltipText: 'SPAWN',
        popupText: 'Player spawn',
        height: '',
        locked: false,
    },
    {//Player Spawn
        category: 'Spawn',
        coordinates: [1804, 2080],
        iconUrl: '../images/icons/spawn-point-icon.webp',
        tooltipText: 'SPAWN',
        popupText: 'Player spawn',
        height: '',
        locked: false,
    },
    {//Player Spawn
        category: 'Spawn',
        coordinates: [2720, 1617],
        iconUrl: '../images/icons/spawn-point-icon.webp',
        tooltipText: 'SPAWN',
        popupText: 'Player spawn',
        height: '',
        locked: false,
    },
    {//Player Spawn
        category: 'Spawn',
        coordinates: [2743, 2468],
        iconUrl: '../images/icons/spawn-point-icon.webp',
        tooltipText: 'SPAWN',
        popupText: 'Player spawn',
        height: '',
        locked: false,
    },
    {//Player Spawn
        category: 'Spawn',
        coordinates: [3142, 1806],
        iconUrl: '../images/icons/spawn-point-icon.webp',
        tooltipText: 'SPAWN',
        popupText: 'Player spawn',
        height: '',
        locked: false,
    },
    {//Player Spawn
        category: 'Spawn',
        coordinates: [3446, 1660],
        iconUrl: '../images/icons/spawn-point-icon.webp',
        tooltipText: 'SPAWN',
        popupText: 'Player spawn',
        height: '',
        locked: false,
    },
    {//Player Spawn
        category: 'Spawn',
        coordinates: [3153, 2328],
        iconUrl: '../images/icons/spawn-point-icon.webp',
        tooltipText: 'SPAWN',
        popupText: 'Player spawn',
        height: '',
        locked: false,
    },
    {//Player Spawn
        category: 'Spawn',
        coordinates: [3627, 2319],
        iconUrl: '../images/icons/spawn-point-icon.webp',
        tooltipText: 'SPAWN',
        popupText: 'Player spawn',
        height: '',
        locked: false,
    },
    {//Player Spawn
        category: 'Spawn',
        coordinates: [3416, 2948],
        iconUrl: '../images/icons/spawn-point-icon.webp',
        tooltipText: 'SPAWN',
        popupText: 'Player spawn',
        height: '',
        locked: false,
    },

    
    {//Weapon Crate
        category: 'Weapon Crate',
        coordinates: [1722, 1659],
        iconUrl: '../images/icons/containers/weapon-crate-icon.webp',
        tooltipText: 'WEAPON CRATE',
        popupText: 'Weapon Crate',
        height: '',
        locked: false,
    },
    {//Weapon Crate
        category: 'Weapon Crate',
        coordinates: [1728, 1696],
        iconUrl: '../images/icons/containers/weapon-crate-icon.webp',
        tooltipText: 'WEAPON CRATE',
        popupText: 'Weapon Crate',
        height: '',
        locked: false,
    },
    {//Weapon Crate
        category: 'Weapon Crate',
        coordinates: [2763, 1131],
        iconUrl: '../images/icons/containers/weapon-crate-icon.webp',
        tooltipText: 'WEAPON CRATE',
        popupText: 'Weapon Crate',
        height: '',
        locked: false,
    },

    
    {//Cement Truck
        category: 'Cement Truck',
        coordinates: [1624, 1537],
        iconUrl: '../images/icons/containers/cement-truck-icon.webp',
        tooltipText: 'CEMENT TRUCK',
        popupText: 'Cement Truck control panel',
        height: '',
        locked: false,
    },
    {//Cement Truck
        category: 'Cement Truck',
        coordinates: [1739, 1652],
        iconUrl: '../images/icons/containers/cement-truck-icon.webp',
        tooltipText: 'CEMENT TRUCK',
        popupText: 'Cement Truck control panel',
        height: '',
        locked: false,
    },
    {//Cement Truck
        category: 'Cement Truck',
        coordinates: [1832, 1587],
        iconUrl: '../images/icons/containers/cement-truck-icon.webp',
        tooltipText: 'CEMENT TRUCK',
        popupText: 'Cement Truck control panel',
        height: '',
        locked: false,
    },
    {//Cement Truck
        category: 'Cement Truck',
        coordinates: [1825, 1347],
        iconUrl: '../images/icons/containers/cement-truck-icon.webp',
        tooltipText: 'CEMENT TRUCK',
        popupText: 'Cement Truck control panel',
        height: '',
        locked: false,
    },
    {//Cement Truck
        category: 'Cement Truck',
        coordinates: [2626, 1907],
        iconUrl: '../images/icons/containers/cement-truck-icon.webp',
        tooltipText: 'CEMENT TRUCK',
        popupText: 'Cement Truck control panel',
        height: '',
        locked: false,
    },
    {//Cement Truck
        category: 'Cement Truck',
        coordinates: [3116, 1530],
        iconUrl: '../images/icons/containers/cement-truck-icon.webp',
        tooltipText: 'CEMENT TRUCK',
        popupText: 'Cement Truck control panel',
        height: '',
        locked: false,
    },

    
    {//Keycard Door
        category: 'Keycard Door',
        coordinates: [2679, 1335],
        iconUrl: '../images/icons/keycard-door-icon-orange.webp',
        tooltipText: 'KEYCARD DOOR',
        popupText: 'East Wing Manager\'s Office',
        height: 'up',
        locked: true,
    },
    {//Keycard Door
        category: 'Keycard Door',
        coordinates: [2739, 2025],
        iconUrl: '../images/icons/keycard-door-icon-orange.webp',
        tooltipText: 'KEYCARD DOOR',
        popupText: 'Substation Tech Room',
        height: 'up',
        locked: true,
    },
    {//Keycard Door
        category: 'Keycard Door',
        coordinates: [2524, 1181],
        iconUrl: '../images/icons/keycard-door-icon-orange.webp',
        tooltipText: 'KEYCARD DOOR',
        popupText: 'West Wing Control Room',
        height: 'up',
        locked: true,
    },
    {//Keycard Door
        category: 'Keycard Door',
        coordinates: [2563, 1276],
        iconUrl: '../images/icons/keycard-door-icon-orange.webp',
        tooltipText: 'KEYCARD DOOR',
        popupText: 'West Wing Monitoring Room',
        height: '',
        locked: true,
    },
    {//Keycard Door
        category: 'Keycard Door',
        coordinates: [1778, 1062],
        iconUrl: '../images/icons/keycard-door-icon-orange.webp',
        tooltipText: 'KEYCARD DOOR',
        popupText: 'Barracks Storage Room',
        height: 'up',
        locked: true,
    },
    {//Keycard Door
        category: 'Keycard Door',
        coordinates: [3432, 2556],
        iconUrl: '../images/icons/keycard-door-icon-orange.webp',
        tooltipText: 'KEYCARD DOOR',
        popupText: 'Ticket Office',
        height: '',
        locked: true,
    },
    {//Keycard Door
        category: 'Keycard Door',
        coordinates: [2747, 1288],
        iconUrl: '../images/icons/keycard-door-icon-orange.webp',
        tooltipText: 'KEYCARD DOOR',
        popupText: 'Equipment Collection Room',
        height: '',
        locked: true,
    },
    {//Keycard Door
        category: 'Keycard Door',
        coordinates: [1569, 1707],
        iconUrl: '../images/icons/keycard-door-icon-orange.webp',
        tooltipText: 'KEYCARD DOOR',
        popupText: 'Cement Plant - Dormitory 201',
        height: 'up',
        locked: true,
    },
    {//Keycard Door
        category: 'Keycard Door',
        coordinates: [3477, 2418],
        iconUrl: '../images/icons/keycard-door-icon-orange.webp',
        tooltipText: 'KEYCARD DOOR',
        popupText: 'Central VIP Room',
        height: 'up',
        locked: true,
    },
    {//Keycard Door
        category: 'Keycard Door',
        coordinates: [1801, 1833],
        iconUrl: '../images/icons/keycard-door-icon-orange.webp',
        tooltipText: 'KEYCARD DOOR',
        popupText: 'Cement Plant Office',
        height: '',
        locked: true,
    },
    {//Keycard Door
        category: 'Keycard Door',
        coordinates: [2567, 1271],
        iconUrl: '../images/icons/keycard-door-icon-orange.webp',
        tooltipText: 'KEYCARD DOOR',
        popupText: 'West Wing Infirmary',
        height: '',
        locked: true,
    },
    {//Keycard Door
        category: 'Keycard Door',
        coordinates: [2548, 2213],
        iconUrl: '../images/icons/keycard-door-icon-orange.webp',
        tooltipText: 'KEYCARD DOOR',
        popupText: 'Substation Dormitory',
        height: '',
        locked: true,
    },
    

    
    // Add more markers here
];
