const markersData = [

    {//Computer
        category: 'Computer',
        coordinates: [1460, 1626],
        iconUrl: '../images/icons/containers/computer-icon.webp',
        tooltipText: 'COMPUTER',
        popupText: 'Computer',
        height: '',
        locked: false,
    },
    {//Computer
        category: 'Computer',
        coordinates: [2377, 2226],
        iconUrl: '../images/icons/containers/computer-icon.webp',
        tooltipText: 'COMPUTER',
        popupText: 'Computer',
        height: '',
        locked: false,
    },
    {//Computer
        category: 'Computer',
        coordinates: [3334, 1781],
        iconUrl: '../images/icons/containers/computer-icon.webp',
        tooltipText: 'COMPUTER',
        popupText: 'Computer',
        height: '',
        locked: false,
    },

    
    {//Computer Bag
        category: 'Computer Bag',
        coordinates: [2596, 2264],
        iconUrl: '../images/icons/containers/premium-storage-box-icon.webp',
        tooltipText: 'COMPUTER BAG',
        popupText: 'Computer Bag',
        height: '',
        locked: false,
    },
    {//Computer Bag
        category: 'Computer Bag',
        coordinates: [2418, 2072],
        iconUrl: '../images/icons/containers/premium-storage-box-icon.webp',
        tooltipText: 'COMPUTER BAG',
        popupText: 'Computer Bag',
        height: '',
        locked: false,
    },
    {//Computer Bag
        category: 'Computer Bag',
        coordinates: [2093, 1950],
        iconUrl: '../images/icons/containers/premium-storage-box-icon.webp',
        tooltipText: 'COMPUTER BAG',
        popupText: 'Computer Bag',
        height: '',
        locked: false,
    },
    {//Computer Bag
        category: 'Computer Bag',
        coordinates: [2487, 1400],
        iconUrl: '../images/icons/containers/premium-storage-box-icon.webp',
        tooltipText: 'COMPUTER BAG',
        popupText: 'Computer Bag',
        height: '',
        locked: false,
    },
    {//Computer Bag
        category: 'Computer Bag',
        coordinates: [1450, 1538],
        iconUrl: '../images/icons/containers/premium-storage-box-icon.webp',
        tooltipText: 'COMPUTER BAG',
        popupText: 'Computer Bag',
        height: '',
        locked: false,
    },

    {//Safe
        category: 'Safe',
        coordinates: [2378, 1203],
        iconUrl: '../images/icons/containers/safe-icon.webp', 
        tooltipText: 'SAFE',
        popupText: 'Safe',
        height: '',
        locked: false,
    },
    {//Safe
        category: 'Safe',
        coordinates: [2633, 1918],
        iconUrl: '../images/icons/containers/safe-icon.webp', 
        tooltipText: 'SAFE',
        popupText: 'Safe',
        height: '',
        locked: false,
    },
    {//Safe
        category: 'Safe',
        coordinates: [2643, 2001],
        iconUrl: '../images/icons/containers/safe-icon.webp', 
        tooltipText: 'SAFE',
        popupText: 'Safe',
        height: '',
        locked: true,
    },
    {//Safe
        category: 'Safe',
        coordinates: [2394, 2086],
        iconUrl: '../images/icons/containers/safe-icon.webp', 
        tooltipText: 'SAFE',
        popupText: 'Safe',
        height: '',
        locked: false,
    },
    {//Safe
        category: 'Safe',
        coordinates: [2426, 2202],
        iconUrl: '../images/icons/containers/safe-icon.webp', 
        tooltipText: 'SAFE',
        popupText: 'Safe',
        height: '',
        locked: true,
    },
    {//Safe
        category: 'Safe',
        coordinates: [2436, 2202],
        iconUrl: '../images/icons/containers/safe-icon.webp', 
        tooltipText: 'SAFE',
        popupText: 'Safe',
        height: '',
        locked: true,
    },
    {//Safe
        category: 'Safe',
        coordinates: [2165, 2252],
        iconUrl: '../images/icons/containers/safe-icon.webp', 
        tooltipText: 'SAFE',
        popupText: 'Safe',
        height: '',
        locked: false,
    },
    {//Safe
        category: 'Safe',
        coordinates: [2131, 2031],
        iconUrl: '../images/icons/containers/safe-icon.webp', 
        tooltipText: 'SAFE',
        popupText: 'Safe',
        height: '',
        locked: false,
    },


    
    {//Server
        category: 'Server',
        coordinates: [2627, 2009],
        iconUrl: '../images/icons/containers/server-icon.webp',
        tooltipText: 'SERVER',
        popupText: 'Server',
        height: '',
        locked: true,
    },
    {//Server
        category: 'Server',
        coordinates: [2641, 2026],
        iconUrl: '../images/icons/containers/server-icon.webp',
        tooltipText: 'SERVER',
        popupText: 'Server',
        height: '',
        locked: true,
    },
    {//Server
        category: 'Server',
        coordinates: [2691, 2259],
        iconUrl: '../images/icons/containers/server-icon.webp',
        tooltipText: 'SERVER',
        popupText: 'Server',
        height: '',
        locked: true,
    },
    {//Server
        category: 'Server',
        coordinates: [2680, 2231],
        iconUrl: '../images/icons/containers/server-icon.webp',
        tooltipText: 'SERVER',
        popupText: 'Server',
        height: '',
        locked: true,
    },
    {//Server
        category: 'Server',
        coordinates: [2145, 2201],
        iconUrl: '../images/icons/containers/server-icon.webp',
        tooltipText: 'SERVER',
        popupText: 'Server',
        height: '',
        locked: false,
    },
    {//Server
        category: 'Server',
        coordinates: [2553, 1385],
        iconUrl: '../images/icons/containers/server-icon.webp',
        tooltipText: 'SERVER',
        popupText: 'Server',
        height: '',
        locked: false,
    },


    // {//Boss
    //     category: 'Boss',
    //     coordinates: [2273, 2916],
    //     iconUrl: '../images/icons/boss-icon-red.webp',
    //     tooltipText: 'LEIS',
    //     popupText: 'Chance for boss spawn.',
    //     height: '',
    //     locked: false,
    // },
    
    
    {//Paid Extract
        category: 'Paid Extract',
        coordinates: [2059, 3504],
        iconUrl: '../images/icons/industrial-extract-icon.webp',
        tooltipText: 'ROCKET EXTRACT',
        popupText: 'After 15 minutes the rocket extract task will become available. Activate it, defend the launch site from AI, and wait for the countdown.',
        height: '',
        locked: false,
    },
    {//Random Extract
        category: 'Random Extract',
        coordinates: [2498, 2608],
        iconUrl: '../images/icons/conditional-extract-icon.webp',
        tooltipText: 'HELICOPTER EXTRACT',
        popupText: 'Helicopter Extract requires pulling 2 levers located in the centrifuge facility and test range. Extracts after around 6 minutes.',
        height: '',
        locked: false,
    },
    {//Normal Extract
        category: 'Normal Extract',
        coordinates: [3066, 3094],
        iconUrl: '../images/icons/conditional-extract-icon.webp',
        tooltipText: 'TEST TRACK EXTRACT',
        popupText: 'Available after 9 minutes. Extract without a backpack. Limited number of extracts per match.',
        height: '',
        locked: false,
    },


    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [2528, 1251],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [2247, 1338],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [1582, 1718],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [1651, 1638],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [2010, 2135],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [2326, 2179],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [2623, 2036],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [2499, 1997],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [2865, 2059],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },
    {//Travel Bag
        category: 'Travel Bag',
        coordinates: [3134, 1767],
        iconUrl: '../images/icons/containers/travel-bag-icon.webp',
        tooltipText: 'TRAVEL BAG',
        popupText: 'Travel Bag',
        height: '',
        locked: false,
    },


    {//Small Safebox
        category: 'Small Safebox',
        coordinates: [2185, 1893],
        iconUrl: '../images/icons/containers/small-safebox-icon.webp',
        tooltipText: 'SMALL SAFEBOX',
        popupText: 'Small Safebox',
        height: '',
        locked: false,
    },
    {//Small Safebox
        category: 'Small Safebox',
        coordinates: [2132, 1992],
        iconUrl: '../images/icons/containers/small-safebox-icon.webp',
        tooltipText: 'SMALL SAFEBOX',
        popupText: 'Small Safebox',
        height: '',
        locked: false,
    },
    {//Small Safebox
        category: 'Small Safebox',
        coordinates: [2577, 2319],
        iconUrl: '../images/icons/containers/small-safebox-icon.webp',
        tooltipText: 'SMALL SAFEBOX',
        popupText: 'Small Safebox',
        height: '',
        locked: false,
    },
    {//Small Safebox
        category: 'Small Safebox',
        coordinates: [2506, 2114],
        iconUrl: '../images/icons/containers/small-safebox-icon.webp',
        tooltipText: 'SMALL SAFEBOX',
        popupText: 'Small Safebox',
        height: '',
        locked: false,
    },

    
    {//Computer Case
        category: 'Computer Case',
        coordinates: [2181, 1958],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Computer Case',
        height: '',
        locked: false,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [2177, 2326],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Computer Case',
        height: '',
        locked: false,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [2226, 2288],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Computer Case',
        height: '',
        locked: false,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [2389, 2229],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Computer Case',
        height: '',
        locked: false,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [2659, 2248],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Computer Case',
        height: '',
        locked: false,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [2659, 2248],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Computer Case',
        height: '',
        locked: false,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [2509, 1945],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Computer Case',
        height: '',
        locked: false,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [2382, 1333],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Computer Case',
        height: '',
        locked: false,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [3334, 1721],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Computer Case',
        height: '',
        locked: false,
    },
    {//Computer Case
        category: 'Computer Case',
        coordinates: [2981, 2973],
        iconUrl: '../images/icons/containers/computer-case-icon.webp',
        tooltipText: 'COMPUTER CASE',
        popupText: 'Computer Case',
        height: '',
        locked: false,
    },

    
    {//LG Weapon Crate
        category: 'LG Weapon Crate',
        coordinates: [3325, 1566],
        iconUrl: '../images/icons/containers/large-weapon-crate-icon.webp',
        tooltipText: 'LARGE WEAPON CRATE',
        popupText: 'Large Weapon Crate',
        height: '',
        locked: false,
    },
    {//LG Weapon Crate
        category: 'LG Weapon Crate',
        coordinates: [3301, 1476],
        iconUrl: '../images/icons/containers/large-weapon-crate-icon.webp',
        tooltipText: 'LARGE WEAPON CRATE',
        popupText: 'Large Weapon Crate',
        height: '',
        locked: false,
    },
    {//LG Weapon Crate
        category: 'LG Weapon Crate',
        coordinates: [3372, 1837],
        iconUrl: '../images/icons/containers/large-weapon-crate-icon.webp',
        tooltipText: 'LARGE WEAPON CRATE',
        popupText: 'Large Weapon Crate',
        height: '',
        locked: false,
    },
    {//LG Weapon Crate
        category: 'LG Weapon Crate',
        coordinates: [2815, 1966],
        iconUrl: '../images/icons/containers/large-weapon-crate-icon.webp',
        tooltipText: 'LARGE WEAPON CRATE',
        popupText: 'Large Weapon Crate',
        height: '',
        locked: false,
    },
    {//LG Weapon Crate
        category: 'LG Weapon Crate',
        coordinates: [2556, 2045],
        iconUrl: '../images/icons/containers/large-weapon-crate-icon.webp',
        tooltipText: 'LARGE WEAPON CRATE',
        popupText: 'Large Weapon Crate',
        height: '',
        locked: false,
    },
    {//LG Weapon Crate
        category: 'LG Weapon Crate',
        coordinates: [2556, 2025],
        iconUrl: '../images/icons/containers/large-weapon-crate-icon.webp',
        tooltipText: 'LARGE WEAPON CRATE',
        popupText: 'Large Weapon Crate',
        height: '',
        locked: false,
    },
    {//LG Weapon Crate
        category: 'LG Weapon Crate',
        coordinates: [2664, 2178],
        iconUrl: '../images/icons/containers/large-weapon-crate-icon.webp',
        tooltipText: 'LARGE WEAPON CRATE',
        popupText: 'Large Weapon Crate',
        height: '',
        locked: false,
    },
    {//LG Weapon Crate
        category: 'LG Weapon Crate',
        coordinates: [2401, 2136],
        iconUrl: '../images/icons/containers/large-weapon-crate-icon.webp',
        tooltipText: 'LARGE WEAPON CRATE',
        popupText: 'Large Weapon Crate',
        height: '',
        locked: false,
    },
    {//LG Weapon Crate
        category: 'LG Weapon Crate',
        coordinates: [2438, 2144],
        iconUrl: '../images/icons/containers/large-weapon-crate-icon.webp',
        tooltipText: 'LARGE WEAPON CRATE',
        popupText: 'Large Weapon Crate',
        height: '',
        locked: false,
    },
    {//LG Weapon Crate
        category: 'LG Weapon Crate',
        coordinates: [2204, 1921],
        iconUrl: '../images/icons/containers/large-weapon-crate-icon.webp',
        tooltipText: 'LARGE WEAPON CRATE',
        popupText: 'Large Weapon Crate',
        height: '',
        locked: false,
    },
    {//LG Weapon Crate
        category: 'LG Weapon Crate',
        coordinates: [2106, 2293],
        iconUrl: '../images/icons/containers/large-weapon-crate-icon.webp',
        tooltipText: 'LARGE WEAPON CRATE',
        popupText: 'Large Weapon Crate',
        height: '',
        locked: false,
    },
    {//LG Weapon Crate
        category: 'LG Weapon Crate',
        coordinates: [1623, 1552],
        iconUrl: '../images/icons/containers/large-weapon-crate-icon.webp',
        tooltipText: 'LARGE WEAPON CRATE',
        popupText: 'Large Weapon Crate',
        height: '',
        locked: false,
    },
    {//LG Weapon Crate
        category: 'LG Weapon Crate',
        coordinates: [2765, 3036],
        iconUrl: '../images/icons/containers/large-weapon-crate-icon.webp',
        tooltipText: 'LARGE WEAPON CRATE',
        popupText: 'Large Weapon Crate',
        height: '',
        locked: false,
    },

    
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [2264, 2164],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [2421, 2118],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [2367, 2085],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [2263, 1936],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [2198, 2077],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [2814, 1978],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [3305, 1687],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [3298, 1591],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [2298, 1328],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [2529, 1383],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [2509, 1383],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [1677, 1714],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },
    {//Ammo Crate
        category: 'Ammo Crate',
        coordinates: [1678, 1982],
        iconUrl: '../images/icons/containers/ammo-crate-icon.webp',
        tooltipText: 'AMMO CRATE',
        popupText: 'Ammo Crate',
        height: '',
        locked: false,
    },

    
    {//Tool Cabinet
        category: 'Tool Cabinet',
        coordinates: [2248, 1310],
        iconUrl: '../images/icons/containers/tool-cabinet-icon.webp',
        tooltipText: 'TOOL CABINET',
        popupText: 'Tool Cabinet',
        height: '',
        locked: false,
    },
    {//Tool Cabinet
        category: 'Tool Cabinet',
        coordinates: [2416, 1214],
        iconUrl: '../images/icons/containers/tool-cabinet-icon.webp',
        tooltipText: 'TOOL CABINET',
        popupText: 'Tool Cabinet',
        height: '',
        locked: false,
    },
    {//Tool Cabinet
        category: 'Tool Cabinet',
        coordinates: [1963, 2213],
        iconUrl: '../images/icons/containers/tool-cabinet-icon.webp',
        tooltipText: 'TOOL CABINET',
        popupText: 'Tool Cabinet',
        height: '',
        locked: false,
    },
    {//Tool Cabinet
        category: 'Tool Cabinet',
        coordinates: [2203, 2184],
        iconUrl: '../images/icons/containers/tool-cabinet-icon.webp',
        tooltipText: 'TOOL CABINET',
        popupText: 'Tool Cabinet',
        height: '',
        locked: false,
    },
    {//Tool Cabinet
        category: 'Tool Cabinet',
        coordinates: [3216, 1585],
        iconUrl: '../images/icons/containers/tool-cabinet-icon.webp',
        tooltipText: 'TOOL CABINET',
        popupText: 'Tool Cabinet',
        height: '',
        locked: false,
    },
    {//Tool Cabinet
        category: 'Tool Cabinet',
        coordinates: [3333, 1551],
        iconUrl: '../images/icons/containers/tool-cabinet-icon.webp',
        tooltipText: 'TOOL CABINET',
        popupText: 'Tool Cabinet',
        height: '',
        locked: false,
    },
    {//Tool Cabinet
        category: 'Tool Cabinet',
        coordinates: [3366, 1827],
        iconUrl: '../images/icons/containers/tool-cabinet-icon.webp',
        tooltipText: 'TOOL CABINET',
        popupText: 'Tool Cabinet',
        height: '',
        locked: false,
    },

    
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [2507, 1396],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'Large Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [2249, 1252],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'Large Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [2560, 1919],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'Large Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [2521, 1961],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'Large Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [2590, 1950],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'Large Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [2675, 2021],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'Large Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [2094, 2024],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'Large Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [2093, 2034],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'Large Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [1977, 2174],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'Large Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [2605, 2250],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'Large Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [2666, 2236],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'Large Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [2580, 2201],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'Large Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [2124, 3456],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'Large Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [3318, 1867],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'Large Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [3219, 1747],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'Large Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [3405, 1771],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'Large Tool Box',
        height: '',
        locked: false,
    },
    {//LG Tool Box
        category: 'LG Tool Box',
        coordinates: [3383, 1831],
        iconUrl: '../images/icons/containers/large-toolbox-icon.webp',
        tooltipText: 'LARGE TOOL BOX',
        popupText: 'Large Tool Box',
        height: '',
        locked: false,
    },


    {//Lab Coat
        category: 'Lab Coat',
        coordinates: [3355, 1682],
        iconUrl: '../images/icons/containers/lab-coat-icon.webp',
        tooltipText: 'LAB COAT',
        popupText: 'Lab Coat',
        height: '',
        locked: false,
    },
    {//Lab Coat
        category: 'Lab Coat',
        coordinates: [3318, 1811],
        iconUrl: '../images/icons/containers/lab-coat-icon.webp',
        tooltipText: 'LAB COAT',
        popupText: 'Lab Coat',
        height: '',
        locked: false,
    },
    {//Lab Coat
        category: 'Lab Coat',
        coordinates: [3396, 1501],
        iconUrl: '../images/icons/containers/lab-coat-icon.webp',
        tooltipText: 'LAB COAT',
        popupText: 'Lab Coat',
        height: '',
        locked: false,
    },
    {//Lab Coat
        category: 'Lab Coat',
        coordinates: [2581, 1992],
        iconUrl: '../images/icons/containers/lab-coat-icon.webp',
        tooltipText: 'LAB COAT',
        popupText: 'Lab Coat',
        height: '',
        locked: false,
    },
    {//Lab Coat
        category: 'Lab Coat',
        coordinates: [2629, 2262],
        iconUrl: '../images/icons/containers/lab-coat-icon.webp',
        tooltipText: 'LAB COAT',
        popupText: 'Lab Coat',
        height: '',
        locked: false,
    },
    {//Lab Coat
        category: 'Lab Coat',
        coordinates: [2443, 2162],
        iconUrl: '../images/icons/containers/lab-coat-icon.webp',
        tooltipText: 'LAB COAT',
        popupText: 'Lab Coat',
        height: '',
        locked: false,
    },
    {//Lab Coat
        category: 'Lab Coat',
        coordinates: [2443, 2151],
        iconUrl: '../images/icons/containers/lab-coat-icon.webp',
        tooltipText: 'LAB COAT',
        popupText: 'Lab Coat',
        height: '',
        locked: false,
    },
    {//Lab Coat
        category: 'Lab Coat',
        coordinates: [2274, 2241],
        iconUrl: '../images/icons/containers/lab-coat-icon.webp',
        tooltipText: 'LAB COAT',
        popupText: 'Lab Coat',
        height: '',
        locked: false,
    },
    {//Lab Coat
        category: 'Lab Coat',
        coordinates: [2157, 2298],
        iconUrl: '../images/icons/containers/lab-coat-icon.webp',
        tooltipText: 'LAB COAT',
        popupText: 'Lab Coat',
        height: '',
        locked: false,
    },
    {//Lab Coat
        category: 'Lab Coat',
        coordinates: [1979, 2313],
        iconUrl: '../images/icons/containers/lab-coat-icon.webp',
        tooltipText: 'LAB COAT',
        popupText: 'Lab Coat',
        height: '',
        locked: false,
    },
    {//Lab Coat
        category: 'Lab Coat',
        coordinates: [2343, 1212],
        iconUrl: '../images/icons/containers/lab-coat-icon.webp',
        tooltipText: 'LAB COAT',
        popupText: 'Lab Coat',
        height: '',
        locked: false,
    },
    {//Lab Coat
        category: 'Lab Coat',
        coordinates: [1442, 1645],
        iconUrl: '../images/icons/containers/lab-coat-icon.webp',
        tooltipText: 'LAB COAT',
        popupText: 'Lab Coat',
        height: '',
        locked: false,
    },
    {//Lab Coat
        category: 'Lab Coat',
        coordinates: [1568, 1597],
        iconUrl: '../images/icons/containers/lab-coat-icon.webp',
        tooltipText: 'LAB COAT',
        popupText: 'Lab Coat',
        height: '',
        locked: false,
    },


    {//Clothing
        category: 'Clothing',
        coordinates: [3401, 1454],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [3385, 1436],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [3384, 1756],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [3390, 1533],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [2663, 2270],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [2659, 2247],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [2618, 2106],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [2342, 2072],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [2335, 2141],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [2199, 2090],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [2125, 2204],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [2199, 1937],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [2199, 1929],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [2210, 1287],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [2242, 1289],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [2230, 1343],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [2209, 1307],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [1461, 1525],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [1462, 1635],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    {//Clothing
        category: 'Clothing',
        coordinates: [2531, 1908],
        iconUrl: '../images/icons/containers/clothing-icon.webp',
        tooltipText: 'CLOTHING',
        popupText: 'Clothing',
        height: '',
        locked: false,
    },
    

    {//Military Medkit
        category: 'Military Medkit',
        coordinates: [2224, 2180],
        iconUrl: '../images/icons/containers/military-med-kit-icon.webp',
        tooltipText: 'MILITARY MEDKIT',
        popupText: 'Military Medkit',
        height: '',
        locked: false,
    },
    {//Military Medkit
        category: 'Military Medkit',
        coordinates: [2119, 2074],
        iconUrl: '../images/icons/containers/military-med-kit-icon.webp',
        tooltipText: 'MILITARY MEDKIT',
        popupText: 'Military Medkit',
        height: '',
        locked: false,
    },
    {//Military Medkit
        category: 'Military Medkit',
        coordinates: [2145, 2090],
        iconUrl: '../images/icons/containers/military-med-kit-icon.webp',
        tooltipText: 'MILITARY MEDKIT',
        popupText: 'Military Medkit',
        height: '',
        locked: false,
    },
    {//Military Medkit
        category: 'Military Medkit',
        coordinates: [2134, 2089],
        iconUrl: '../images/icons/containers/military-med-kit-icon.webp',
        tooltipText: 'MILITARY MEDKIT',
        popupText: 'Military Medkit',
        height: '',
        locked: false,
    },
    {//Military Medkit
        category: 'Military Medkit',
        coordinates: [2240, 1994],
        iconUrl: '../images/icons/containers/military-med-kit-icon.webp',
        tooltipText: 'MILITARY MEDKIT',
        popupText: 'Military Medkit',
        height: '',
        locked: false,
    },
    {//Military Medkit
        category: 'Military Medkit',
        coordinates: [2215, 2076],
        iconUrl: '../images/icons/containers/military-med-kit-icon.webp',
        tooltipText: 'MILITARY MEDKIT',
        popupText: 'Military Medkit',
        height: '',
        locked: false,
    },
    {//Military Medkit
        category: 'Military Medkit',
        coordinates: [1836, 1530],
        iconUrl: '../images/icons/containers/military-med-kit-icon.webp',
        tooltipText: 'MILITARY MEDKIT',
        popupText: 'Military Medkit',
        height: '',
        locked: false,
    },
    {//Military Medkit
        category: 'Military Medkit',
        coordinates: [1581, 1574],
        iconUrl: '../images/icons/containers/military-med-kit-icon.webp',
        tooltipText: 'MILITARY MEDKIT',
        popupText: 'Military Medkit',
        height: '',
        locked: false,
    },

    
    {//Medical Pile
        category: 'Medical Pile',
        coordinates: [1502, 1884],
        iconUrl: '../images/icons/containers/pile-of-medical-supplies-icon.webp',
        tooltipText: 'MEDICAL PILE',
        popupText: 'Pile of medical supplies',
        height: '',
        locked: false,
    },
    {//Medical Pile
        category: 'Medical Pile',
        coordinates: [2258, 1357],
        iconUrl: '../images/icons/containers/pile-of-medical-supplies-icon.webp',
        tooltipText: 'MEDICAL PILE',
        popupText: 'Pile of medical supplies',
        height: '',
        locked: false,
    },
    {//Medical Pile
        category: 'Medical Pile',
        coordinates: [2142, 2118],
        iconUrl: '../images/icons/containers/pile-of-medical-supplies-icon.webp',
        tooltipText: 'MEDICAL PILE',
        popupText: 'Pile of medical supplies',
        height: '',
        locked: false,
    },
    {//Medical Pile
        category: 'Medical Pile',
        coordinates: [2130, 2062],
        iconUrl: '../images/icons/containers/pile-of-medical-supplies-icon.webp',
        tooltipText: 'MEDICAL PILE',
        popupText: 'Pile of medical supplies',
        height: '',
        locked: false,
    },
    {//Medical Pile
        category: 'Medical Pile',
        coordinates: [2163, 1952],
        iconUrl: '../images/icons/containers/pile-of-medical-supplies-icon.webp',
        tooltipText: 'MEDICAL PILE',
        popupText: 'Pile of medical supplies',
        height: '',
        locked: false,
    },
    {//Medical Pile
        category: 'Medical Pile',
        coordinates: [2202, 2220],
        iconUrl: '../images/icons/containers/pile-of-medical-supplies-icon.webp',
        tooltipText: 'MEDICAL PILE',
        popupText: 'Pile of medical supplies',
        height: '',
        locked: false,
    },
    {//Medical Pile
        category: 'Medical Pile',
        coordinates: [2823, 1553],
        iconUrl: '../images/icons/containers/pile-of-medical-supplies-icon.webp',
        tooltipText: 'MEDICAL PILE',
        popupText: 'Pile of medical supplies',
        height: '',
        locked: false,
    },

    
    {//Briefcase
        category: 'Briefcase',
        coordinates: [2645, 2276],
        iconUrl: '../images/icons/containers/briefcase-icon.webp',
        tooltipText: 'BRIEFCASE',
        popupText: 'Briefcase',
        height: '',
        locked: false,
    },
    {//Briefcase
        category: 'Briefcase',
        coordinates: [2398, 2198],
        iconUrl: '../images/icons/containers/briefcase-icon.webp',
        tooltipText: 'BRIEFCASE',
        popupText: 'Briefcase',
        height: '',
        locked: false,
    },
    {//Briefcase
        category: 'Briefcase',
        coordinates: [2118, 1936],
        iconUrl: '../images/icons/containers/briefcase-icon.webp',
        tooltipText: 'BRIEFCASE',
        popupText: 'Briefcase',
        height: '',
        locked: false,
    },
    {//Briefcase
        category: 'Briefcase',
        coordinates: [1587, 1575],
        iconUrl: '../images/icons/containers/briefcase-icon.webp',
        tooltipText: 'BRIEFCASE',
        popupText: 'Briefcase',
        height: '',
        locked: false,
    },
    {//Briefcase
        category: 'Briefcase',
        coordinates: [2512, 1403],
        iconUrl: '../images/icons/containers/briefcase-icon.webp',
        tooltipText: 'BRIEFCASE',
        popupText: 'Briefcase',
        height: '',
        locked: false,
    },
    {//Briefcase
        category: 'Briefcase',
        coordinates: [2531, 1399],
        iconUrl: '../images/icons/containers/briefcase-icon.webp',
        tooltipText: 'BRIEFCASE',
        popupText: 'Briefcase',
        height: '',
        locked: false,
    },


    {//Premium Storage
        category: 'Premium Storage',
        coordinates: [2538, 1395],
        iconUrl: '../images/icons/containers/premium-storage-box-icon.webp',
        tooltipText: 'PREMIUM STORAGE BOX',
        popupText: 'Premium Storage Box',
        height: '',
        locked: false,
    },
    {//Premium Storage
        category: 'Premium Storage',
        coordinates: [2302, 1549],
        iconUrl: '../images/icons/containers/premium-storage-box-icon.webp',
        tooltipText: 'PREMIUM STORAGE BOX',
        popupText: 'Premium Storage Box',
        height: '',
        locked: false,
    },
    {//Premium Storage
        category: 'Premium Storage',
        coordinates: [2192, 1884],
        iconUrl: '../images/icons/containers/premium-storage-box-icon.webp',
        tooltipText: 'PREMIUM STORAGE BOX',
        popupText: 'Premium Storage Box',
        height: '',
        locked: false,
    },
    {//Premium Storage
        category: 'Premium Storage',
        coordinates: [2625, 1906],
        iconUrl: '../images/icons/containers/premium-storage-box-icon.webp',
        tooltipText: 'PREMIUM STORAGE BOX',
        popupText: 'Premium Storage Box',
        height: '',
        locked: false,
    },
    {//Premium Storage
        category: 'Premium Storage',
        coordinates: [2512, 2181],
        iconUrl: '../images/icons/containers/premium-storage-box-icon.webp',
        tooltipText: 'PREMIUM STORAGE BOX',
        popupText: 'Premium Storage Box',
        height: '',
        locked: false,
    },
    {//Premium Storage
        category: 'Premium Storage',
        coordinates: [2666, 2265],
        iconUrl: '../images/icons/containers/premium-storage-box-icon.webp',
        tooltipText: 'PREMIUM STORAGE BOX',
        popupText: 'Premium Storage Box',
        height: '',
        locked: false,
    },
    {//Premium Storage
        category: 'Premium Storage',
        coordinates: [2578, 2319],
        iconUrl: '../images/icons/containers/premium-storage-box-icon.webp',
        tooltipText: 'PREMIUM STORAGE BOX',
        popupText: 'Premium Storage Box',
        height: '',
        locked: false,
    },
    {//Premium Storage
        category: 'Premium Storage',
        coordinates: [2574, 2333],
        iconUrl: '../images/icons/containers/premium-storage-box-icon.webp',
        tooltipText: 'PREMIUM STORAGE BOX',
        popupText: 'Premium Storage Box',
        height: '',
        locked: false,
    },
    {//Premium Storage
        category: 'Premium Storage',
        coordinates: [3326, 1683],
        iconUrl: '../images/icons/containers/premium-storage-box-icon.webp',
        tooltipText: 'PREMIUM STORAGE BOX',
        popupText: 'Premium Storage Box',
        height: '',
        locked: false,
    },

    
    {//Drawers
        category: 'Drawers',
        coordinates: [3329, 1809],
        iconUrl: '../images/icons/containers/drawer-icon.webp',
        tooltipText: 'DRAWERS',
        popupText: 'Drawers',
        height: '',
        locked: false,
    },
    {//Drawers
        category: 'Drawers',
        coordinates: [3328, 1761],
        iconUrl: '../images/icons/containers/drawer-icon.webp',
        tooltipText: 'DRAWERS',
        popupText: 'Drawers',
        height: '',
        locked: false,
    },
    {//Drawers
        category: 'Drawers',
        coordinates: [3321, 1728],
        iconUrl: '../images/icons/containers/drawer-icon.webp',
        tooltipText: 'DRAWERS',
        popupText: 'Drawers',
        height: '',
        locked: false,
    },
    {//Drawers
        category: 'Drawers',
        coordinates: [2956, 2951],
        iconUrl: '../images/icons/containers/drawer-icon.webp',
        tooltipText: 'DRAWERS',
        popupText: 'Drawers',
        height: '',
        locked: false,
    },
    {//Drawers
        category: 'Drawers',
        coordinates: [2569, 2243],
        iconUrl: '../images/icons/containers/drawer-icon.webp',
        tooltipText: 'DRAWERS',
        popupText: 'Drawers',
        height: '',
        locked: false,
    },
    {//Drawers
        category: 'Drawers',
        coordinates: [2274, 2266],
        iconUrl: '../images/icons/containers/drawer-icon.webp',
        tooltipText: 'DRAWERS',
        popupText: 'Drawers',
        height: '',
        locked: false,
    },
    {//Drawers
        category: 'Drawers',
        coordinates: [2354, 2234],
        iconUrl: '../images/icons/containers/drawer-icon.webp',
        tooltipText: 'DRAWERS',
        popupText: 'Drawers',
        height: '',
        locked: false,
    },
    {//Drawers
        category: 'Drawers',
        coordinates: [2095, 1920],
        iconUrl: '../images/icons/containers/drawer-icon.webp',
        tooltipText: 'DRAWERS',
        popupText: 'Drawers',
        height: '',
        locked: false,
    },
    {//Drawers
        category: 'Drawers',
        coordinates: [2491, 1922],
        iconUrl: '../images/icons/containers/drawer-icon.webp',
        tooltipText: 'DRAWERS',
        popupText: 'Drawers',
        height: '',
        locked: false,
    },
    {//Drawers
        category: 'Drawers',
        coordinates: [2523, 1401],
        iconUrl: '../images/icons/containers/drawer-icon.webp',
        tooltipText: 'DRAWERS',
        popupText: 'Drawers',
        height: '',
        locked: false,
    },
    {//Drawers
        category: 'Drawers',
        coordinates: [2223, 1360],
        iconUrl: '../images/icons/containers/drawer-icon.webp',
        tooltipText: 'DRAWERS',
        popupText: 'Drawers',
        height: '',
        locked: false,
    },
    {//Drawers
        category: 'Drawers',
        coordinates: [2230, 1202],
        iconUrl: '../images/icons/containers/drawer-icon.webp',
        tooltipText: 'DRAWERS',
        popupText: 'Drawers',
        height: '',
        locked: false,
    },
    {//Drawers
        category: 'Drawers',
        coordinates: [2210, 1246],
        iconUrl: '../images/icons/containers/drawer-icon.webp',
        tooltipText: 'DRAWERS',
        popupText: 'Drawers',
        height: '',
        locked: false,
    },


    {//Climbing Bag
        category: 'Climbing Bag',
        coordinates: [2190, 1890],
        iconUrl: '../images/icons/containers/premium-storage-box-icon.webp',
        tooltipText: 'CLIMBING BAG',
        popupText: 'Climbing bag',
        height: '',
        locked: false,
    },
    {//Climbing Bag
        category: 'Climbing Bag',
        coordinates: [2183, 1897],
        iconUrl: '../images/icons/containers/premium-storage-box-icon.webp',
        tooltipText: 'CLIMBING BAG',
        popupText: 'Climbing bag',
        height: '',
        locked: false,
    },
    {//Climbing Bag
        category: 'Climbing Bag',
        coordinates: [2367, 1293],
        iconUrl: '../images/icons/containers/premium-storage-box-icon.webp',
        tooltipText: 'CLIMBING BAG',
        popupText: 'Climbing bag',
        height: '',
        locked: false,
    },
    {//Climbing Bag
        category: 'Climbing Bag',
        coordinates: [2571, 2323],
        iconUrl: '../images/icons/containers/premium-storage-box-icon.webp',
        tooltipText: 'CLIMBING BAG',
        popupText: 'Climbing bag',
        height: '',
        locked: false,
    },

    
    {//Courier Carton
        category: 'Courier Carton',
        coordinates: [2246, 2248],
        iconUrl: '../images/icons/containers/courier-carton-icon.webp',
        tooltipText: 'COURIER CARTON',
        popupText: 'Courier Carton',
        height: '',
        locked: false,
    },
    {//Courier Carton
        category: 'Courier Carton',
        coordinates: [2238, 2267],
        iconUrl: '../images/icons/containers/courier-carton-icon.webp',
        tooltipText: 'COURIER CARTON',
        popupText: 'Courier Carton',
        height: '',
        locked: false,
    },
    {//Courier Carton
        category: 'Courier Carton',
        coordinates: [2172, 2301],
        iconUrl: '../images/icons/containers/courier-carton-icon.webp',
        tooltipText: 'COURIER CARTON',
        popupText: 'Courier Carton',
        height: '',
        locked: false,
    },
    {//Courier Carton
        category: 'Courier Carton',
        coordinates: [2188, 2165],
        iconUrl: '../images/icons/containers/courier-carton-icon.webp',
        tooltipText: 'COURIER CARTON',
        popupText: 'Courier Carton',
        height: '',
        locked: false,
    },
    {//Courier Carton
        category: 'Courier Carton',
        coordinates: [2122, 1935],
        iconUrl: '../images/icons/containers/courier-carton-icon.webp',
        tooltipText: 'COURIER CARTON',
        popupText: 'Courier Carton',
        height: '',
        locked: false,
    },
    {//Courier Carton
        category: 'Courier Carton',
        coordinates: [2511, 1928],
        iconUrl: '../images/icons/containers/courier-carton-icon.webp',
        tooltipText: 'COURIER CARTON',
        popupText: 'Courier Carton',
        height: '',
        locked: false,
    },
    {//Courier Carton
        category: 'Courier Carton',
        coordinates: [2500, 1979],
        iconUrl: '../images/icons/containers/courier-carton-icon.webp',
        tooltipText: 'COURIER CARTON',
        popupText: 'Courier Carton',
        height: '',
        locked: false,
    },
    {//Courier Carton
        category: 'Courier Carton',
        coordinates: [1471, 1570],
        iconUrl: '../images/icons/containers/courier-carton-icon.webp',
        tooltipText: 'COURIER CARTON',
        popupText: 'Courier Carton',
        height: '',
        locked: false,
    },
    {//Courier Carton
        category: 'Courier Carton',
        coordinates: [2272, 1211],
        iconUrl: '../images/icons/containers/courier-carton-icon.webp',
        tooltipText: 'COURIER CARTON',
        popupText: 'Courier Carton',
        height: '',
        locked: false,
    },
    {//Courier Carton
        category: 'Courier Carton',
        coordinates: [2393, 1221],
        iconUrl: '../images/icons/containers/courier-carton-icon.webp',
        tooltipText: 'COURIER CARTON',
        popupText: 'Courier Carton',
        height: '',
        locked: false,
    },
    {//Courier Carton
        category: 'Courier Carton',
        coordinates: [2396, 1233],
        iconUrl: '../images/icons/containers/courier-carton-icon.webp',
        tooltipText: 'COURIER CARTON',
        popupText: 'Courier Carton',
        height: '',
        locked: false,
    },
    {//Courier Carton
        category: 'Courier Carton',
        coordinates: [2524, 1309],
        iconUrl: '../images/icons/containers/courier-carton-icon.webp',
        tooltipText: 'COURIER CARTON',
        popupText: 'Courier Carton',
        height: '',
        locked: false,
    },
    {//Courier Carton
        category: 'Courier Carton',
        coordinates: [2492, 1331],
        iconUrl: '../images/icons/containers/courier-carton-icon.webp',
        tooltipText: 'COURIER CARTON',
        popupText: 'Courier Carton',
        height: '',
        locked: false,
    },
    {//Courier Carton
        category: 'Courier Carton',
        coordinates: [3336, 1781],
        iconUrl: '../images/icons/containers/courier-carton-icon.webp',
        tooltipText: 'COURIER CARTON',
        popupText: 'Courier Carton',
        height: '',
        locked: false,
    },
    {//Courier Carton
        category: 'Courier Carton',
        coordinates: [3362, 1766],
        iconUrl: '../images/icons/containers/courier-carton-icon.webp',
        tooltipText: 'COURIER CARTON',
        popupText: 'Courier Carton',
        height: '',
        locked: false,
    },
    {//Courier Carton
        category: 'Courier Carton',
        coordinates: [3352, 1753],
        iconUrl: '../images/icons/containers/courier-carton-icon.webp',
        tooltipText: 'COURIER CARTON',
        popupText: 'Courier Carton',
        height: '',
        locked: false,
    },
    {//Courier Carton
        category: 'Courier Carton',
        coordinates: [3333, 1741],
        iconUrl: '../images/icons/containers/courier-carton-icon.webp',
        tooltipText: 'COURIER CARTON',
        popupText: 'Courier Carton',
        height: '',
        locked: false,
    },
    {//Courier Carton
        category: 'Courier Carton',
        coordinates: [3349, 1717],
        iconUrl: '../images/icons/containers/courier-carton-icon.webp',
        tooltipText: 'COURIER CARTON',
        popupText: 'Courier Carton',
        height: '',
        locked: false,
    },


    {//Flight Case
        category: 'Flight Case',
        coordinates: [2794, 1756],
        iconUrl: '../images/icons/containers/flight-case-icon.webp',
        tooltipText: 'FLIGHT CASE',
        popupText: 'Flight Case',
        height: '',
        locked: false,
    },
    {//Flight Case
        category: 'Flight Case',
        coordinates: [2670, 1957],
        iconUrl: '../images/icons/containers/flight-case-icon.webp',
        tooltipText: 'FLIGHT CASE',
        popupText: 'Flight Case',
        height: '',
        locked: false,
    },
    {//Flight Case
        category: 'Flight Case',
        coordinates: [2619, 2224],
        iconUrl: '../images/icons/containers/flight-case-icon.webp',
        tooltipText: 'FLIGHT CASE',
        popupText: 'Flight Case',
        height: '',
        locked: false,
    },
    {//Flight Case
        category: 'Flight Case',
        coordinates: [2568, 2120],
        iconUrl: '../images/icons/containers/flight-case-icon.webp',
        tooltipText: 'FLIGHT CASE',
        popupText: 'Flight Case',
        height: '',
        locked: false,
    },
    {//Flight Case
        category: 'Flight Case',
        coordinates: [2176, 2079],
        iconUrl: '../images/icons/containers/flight-case-icon.webp',
        tooltipText: 'FLIGHT CASE',
        popupText: 'Flight Case',
        height: '',
        locked: false,
    },
    {//Flight Case
        category: 'Flight Case',
        coordinates: [2150, 2281],
        iconUrl: '../images/icons/containers/flight-case-icon.webp',
        tooltipText: 'FLIGHT CASE',
        popupText: 'Flight Case',
        height: '',
        locked: false,
    },
    {//Flight Case
        category: 'Flight Case',
        coordinates: [2547, 1364],
        iconUrl: '../images/icons/containers/flight-case-icon.webp',
        tooltipText: 'FLIGHT CASE',
        popupText: 'Flight Case',
        height: '',
        locked: false,
    },
    {//Flight Case
        category: 'Flight Case',
        coordinates: [1607, 1536],
        iconUrl: '../images/icons/containers/flight-case-icon.webp',
        tooltipText: 'FLIGHT CASE',
        popupText: 'Flight Case',
        height: '',
        locked: false,
    },


    {//Dumpster
        category: 'Dumpster',
        coordinates: [1546, 1689],
        iconUrl: '../images/icons/containers/dumpster-icon.webp',
        tooltipText: 'DUMPSTER',
        popupText: 'Dumpster',
        height: '',
        locked: false,
    },
    {//Dumpster
        category: 'Dumpster',
        coordinates: [2429, 1424],
        iconUrl: '../images/icons/containers/dumpster-icon.webp',
        tooltipText: 'DUMPSTER',
        popupText: 'Dumpster',
        height: '',
        locked: false,
    },
    {//Dumpster
        category: 'Dumpster',
        coordinates: [3197, 1212],
        iconUrl: '../images/icons/containers/dumpster-icon.webp',
        tooltipText: 'DUMPSTER',
        popupText: 'Dumpster',
        height: '',
        locked: false,
    },
    {//Dumpster
        category: 'Dumpster',
        coordinates: [2779, 3034],
        iconUrl: '../images/icons/containers/dumpster-icon.webp',
        tooltipText: 'DUMPSTER',
        popupText: 'Dumpster',
        height: '',
        locked: false,
    },
    {//Dumpster
        category: 'Dumpster',
        coordinates: [2134, 3131],
        iconUrl: '../images/icons/containers/dumpster-icon.webp',
        tooltipText: 'DUMPSTER',
        popupText: 'Dumpster',
        height: '',
        locked: false,
    },


    {//Field Supply Box
        category: 'Field Supply',
        coordinates: [1935, 3348],
        iconUrl: '../images/icons/containers/field-supply-box-icon.webp',
        tooltipText: 'FIELD SUPPLY BOX',
        popupText: 'Field Supply Box',
        height: '',
        locked: false,
    },
    {//Field Supply Box
        category: 'Field Supply',
        coordinates: [1881, 3272],
        iconUrl: '../images/icons/containers/field-supply-box-icon.webp',
        tooltipText: 'FIELD SUPPLY BOX',
        popupText: 'Field Supply Box',
        height: '',
        locked: false,
    },
    {//Field Supply Box
        category: 'Field Supply',
        coordinates: [2182, 3365],
        iconUrl: '../images/icons/containers/field-supply-box-icon.webp',
        tooltipText: 'FIELD SUPPLY BOX',
        popupText: 'Field Supply Box',
        height: '',
        locked: false,
    },
    {//Field Supply Box
        category: 'Field Supply',
        coordinates: [2178, 3205],
        iconUrl: '../images/icons/containers/field-supply-box-icon.webp',
        tooltipText: 'FIELD SUPPLY BOX',
        popupText: 'Field Supply Box',
        height: '',
        locked: false,
    },
    {//Field Supply Box
        category: 'Field Supply',
        coordinates: [2679, 2900],
        iconUrl: '../images/icons/containers/field-supply-box-icon.webp',
        tooltipText: 'FIELD SUPPLY BOX',
        popupText: 'Field Supply Box',
        height: '',
        locked: false,
    },
    {//Field Supply Box
        category: 'Field Supply',
        coordinates: [2235, 2171],
        iconUrl: '../images/icons/containers/field-supply-box-icon.webp',
        tooltipText: 'FIELD SUPPLY BOX',
        popupText: 'Field Supply Box',
        height: '',
        locked: false,
    },
    {//Field Supply Box
        category: 'Field Supply',
        coordinates: [2530, 2042],
        iconUrl: '../images/icons/containers/field-supply-box-icon.webp',
        tooltipText: 'FIELD SUPPLY BOX',
        popupText: 'Field Supply Box',
        height: '',
        locked: false,
    },
    {//Field Supply Box
        category: 'Field Supply',
        coordinates: [3249, 2187],
        iconUrl: '../images/icons/containers/field-supply-box-icon.webp',
        tooltipText: 'FIELD SUPPLY BOX',
        popupText: 'Field Supply Box',
        height: '',
        locked: false,
    },


    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [3036, 2009],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: '',
        locked: false,
    },
    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [2629, 2720],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: '',
        locked: false,
    },
    {//Bird Nest
        category: 'Bird Nest',
        coordinates: [1884, 2402],
        iconUrl: '../images/icons/containers/bird-nest-icon.webp',
        tooltipText: 'BIRD NEST',
        popupText: 'Bird Nest',
        height: '',
        locked: false,
    },

    
    {//Stash
        category: 'Stash',
        coordinates: [2474, 2734],
        iconUrl: '../images/icons/containers/hidden-stash-icon.webp',
        tooltipText: 'STASH',
        popupText: 'Stash',
        height: '',
        locked: false,
    },
    {//Stash
        category: 'Stash',
        coordinates: [3333, 2211],
        iconUrl: '../images/icons/containers/hidden-stash-icon.webp',
        tooltipText: 'STASH',
        popupText: 'Stash',
        height: '',
        locked: false,
    },
    {//Stash
        category: 'Stash',
        coordinates: [2313, 1557],
        iconUrl: '../images/icons/containers/hidden-stash-icon.webp',
        tooltipText: 'STASH',
        popupText: 'Stash',
        height: '',
        locked: false,
    },
    {//Stash
        category: 'Stash',
        coordinates: [1777, 1521],
        iconUrl: '../images/icons/containers/hidden-stash-icon.webp',
        tooltipText: 'STASH',
        popupText: 'Stash',
        height: '',
        locked: false,
    },


    {//Suitcase
        category: 'Suitcase',
        coordinates: [1712, 1561],
        iconUrl: '../images/icons/containers/suitcase-icon.webp',
        tooltipText: 'SUITCASE',
        popupText: 'Suitcase',
        height: '',
        locked: false,
    },
    {//Suitcase
        category: 'Suitcase',
        coordinates: [1471, 1645],
        iconUrl: '../images/icons/containers/suitcase-icon.webp',
        tooltipText: 'SUITCASE',
        popupText: 'Suitcase',
        height: '',
        locked: false,
    },
    {//Suitcase
        category: 'Suitcase',
        coordinates: [2156, 2076],
        iconUrl: '../images/icons/containers/suitcase-icon.webp',
        tooltipText: 'SUITCASE',
        popupText: 'Suitcase',
        height: '',
        locked: false,
    },

    
    {//Player Spawn
        category: 'Spawn',
        coordinates: [1969, 3407],
        iconUrl: '../images/icons/spawn-point-icon.webp',
        tooltipText: 'SPAWN',
        popupText: 'Player Spawn',
        height: '',
        locked: false,
    },
    {//Player Spawn
        category: 'Spawn',
        coordinates: [1397, 2113],
        iconUrl: '../images/icons/spawn-point-icon.webp',
        tooltipText: 'SPAWN',
        popupText: 'Player Spawn',
        height: '',
        locked: false,
    },
    {//Player Spawn
        category: 'Spawn',
        coordinates: [1394, 1453],
        iconUrl: '../images/icons/spawn-point-icon.webp',
        tooltipText: 'SPAWN',
        popupText: 'Player Spawn',
        height: '',
        locked: false,
    },
    {//Player Spawn
        category: 'Spawn',
        coordinates: [3221, 2455],
        iconUrl: '../images/icons/spawn-point-icon.webp',
        tooltipText: 'SPAWN',
        popupText: 'Player Spawn',
        height: '',
        locked: false,
    },
    {//Player Spawn
        category: 'Spawn',
        coordinates: [3487, 1921],
        iconUrl: '../images/icons/spawn-point-icon.webp',
        tooltipText: 'SPAWN',
        popupText: 'Player Spawn',
        height: '',
        locked: false,
    },
    {//Player Spawn
        category: 'Spawn',
        coordinates: [3125, 1156],
        iconUrl: '../images/icons/spawn-point-icon.webp',
        tooltipText: 'SPAWN',
        popupText: 'Player Spawn',
        height: '',
        locked: false,
    },
    {//Player Spawn
        category: 'Spawn',
        coordinates: [2254, 1192],
        iconUrl: '../images/icons/spawn-point-icon.webp',
        tooltipText: 'SPAWN',
        popupText: 'Player Spawn',
        height: '',
        locked: false,
    },
    {//Player Spawn
        category: 'Spawn',
        coordinates: [2784, 1634],
        iconUrl: '../images/icons/spawn-point-icon.webp',
        tooltipText: 'SPAWN',
        popupText: 'Player Spawn',
        height: '',
        locked: false,
    },
    
    {//Weapon Crate
        category: 'Weapon Crate',
        coordinates: [2135, 2173],
        iconUrl: '../images/icons/containers/weapon-crate-icon.webp',
        tooltipText: 'WEAPON CRATE',
        popupText: 'Weapon Crate',
        height: '',
        locked: false,
    },
    {//Weapon Crate
        category: 'Weapon Crate',
        coordinates: [2104, 2293],
        iconUrl: '../images/icons/containers/weapon-crate-icon.webp',
        tooltipText: 'WEAPON CRATE',
        popupText: 'Weapon Crate',
        height: '',
        locked: false,
    },
    {//Weapon Crate
        category: 'Weapon Crate',
        coordinates: [2607, 2050],
        iconUrl: '../images/icons/containers/weapon-crate-icon.webp',
        tooltipText: 'WEAPON CRATE',
        popupText: 'Weapon Crate',
        height: '',
        locked: false,
    },
    {//Weapon Crate
        category: 'Weapon Crate',
        coordinates: [2544, 2045],
        iconUrl: '../images/icons/containers/weapon-crate-icon.webp',
        tooltipText: 'WEAPON CRATE',
        popupText: 'Weapon Crate',
        height: '',
        locked: false,
    },

    
    // {//Cement Truck
    //     category: 'Cement Truck',
    //     coordinates: [2959, 2968],
    //     iconUrl: '../images/icons/containers/cement-truck-icon.webp',
    //     tooltipText: 'CEMENT TRUCK',
    //     popupText: 'Cement Truck control panel',
    //     height: '',
    //     locked: false,
    // },
    
    
    {//Keycard Door
        category: 'Keycard Door',
        coordinates: [2418, 2153],
        iconUrl: '../images/icons/keycard-door-icon-orange.webp',
        tooltipText: 'CEO Office Reception Room',
        popupText: 'CEO Office Reception Room',
        height: 'up',
        locked: true,
    },
    {//Keycard Door
        category: 'Keycard Door',
        coordinates: [2629, 2240],
        iconUrl: '../images/icons/keycard-door-icon-orange.webp',
        tooltipText: 'Black Chamber Server Room',
        popupText: 'Black Chamber Server Room',
        height: '',
        locked: true,
    },
    {//Keycard Door
        category: 'Keycard Door',
        coordinates: [2840, 2357],
        iconUrl: '../images/icons/keycard-door-icon-orange.webp',
        tooltipText: 'Eastern Suspension Bridge',
        popupText: 'Eastern Suspension Bridge',
        height: '',
        locked: true,
    },
    {//Keycard Door
        category: 'Keycard Door',
        coordinates: [2580, 1996],
        iconUrl: '../images/icons/keycard-door-icon-orange.webp',
        tooltipText: 'Test Range Core',
        popupText: 'Test Range Core',
        height: '',
        locked: true,
    },
    {//Keycard Door
        category: 'Keycard Door',
        coordinates: [2552, 2006],
        iconUrl: '../images/icons/keycard-door-icon-orange.webp',
        tooltipText: 'Test Range Data Center',
        popupText: 'Test Range Data Center',
        height: '',
        locked: true,
    },
    {//Keycard Door
        category: 'Keycard Door',
        coordinates: [3354, 1761],
        iconUrl: '../images/icons/keycard-door-icon-orange.webp',
        tooltipText: 'Assembly Workshop 2F Lab',
        popupText: 'Assembly Workshop 2F Lab',
        height: 'up',
        locked: true,
    },
    {//Keycard Door
        category: 'Keycard Door',
        coordinates: [1846, 1954],
        iconUrl: '../images/icons/keycard-door-icon-orange.webp',
        tooltipText: 'West Gate',
        popupText: 'West Gate',
        height: '',
        locked: true,
    },
    {//Keycard Door
        category: 'Keycard Door',
        coordinates: [2793, 1579],
        iconUrl: '../images/icons/keycard-door-icon-orange.webp',
        tooltipText: 'Employee Passage',
        popupText: 'Employee Passage',
        height: '',
        locked: true,
    },
    {//Keycard Door
        category: 'Keycard Door',
        coordinates: [1475, 1653],
        iconUrl: '../images/icons/keycard-door-icon-orange.webp',
        tooltipText: 'No. 3 Dormitory Back Room',
        popupText: 'No. 3 Dormitory Back Room',
        height: '',
        locked: true,
    },
    {//Keycard Door
        category: 'Keycard Door',
        coordinates: [2343, 1216],
        iconUrl: '../images/icons/keycard-door-icon-orange.webp',
        tooltipText: 'Central Command Room 3F',
        popupText: 'Central Command Room 3F',
        height: 'up',
        locked: true,
    },
    {//Keycard Door
        category: 'Keycard Door',
        coordinates: [2596, 2031],
        iconUrl: '../images/icons/keycard-door-icon-orange.webp',
        tooltipText: 'Test Range Glass Room',
        popupText: 'Test Range Glass Room',
        height: '',
        locked: true,
    },
    {//Keycard Door
        category: 'Keycard Door',
        coordinates: [2142, 2100],
        iconUrl: '../images/icons/keycard-door-icon-orange.webp',
        tooltipText: 'Buoyancy Lab Infirmary',
        popupText: 'Buoyancy Lab Infirmary',
        height: '',
        locked: true,
    },
    
    // {//Secret Crate
    //     category: 'Secret Crate',
    //     coordinates: [3085, 1117],
    //     iconUrl: '../images/icons/containers/secret-crate-icon.webp',
    //     tooltipText: 'PROTOCOL CRATE 1',
    //     popupText: 'Secret Protocol Crate',
    //     height: 'up',
    //     locked: false,
    // },

    
    // {//Easter Egg
    //     category: 'Easter Egg',
    //     coordinates: [3149, 2266],
    //     iconUrl: '../images/icons/event-trigger-icon.webp',
    //     tooltipText: 'BUNKER LADDER',
    //     popupText: 'Bunker Ladder',
    //     height: '',
    //     locked: false,
    // },

    
    // Add more markers here
];
